### ISSUE TITLE
second config cannot be used during deploy

### ISSUE THREAD

**Issue by siyuniuali** [Serverless-Devs/Serverless-Devs#111]
During the procedure of a quick start flask project using open API explorer.

1. `s config add` set the second account id with an access key, and then deletes the first one.
2. `s deploy` select the second config access twice, get error report as following:

![image](https://user-images.githubusercontent.com/84389274/121012399-43380c80-c7ca-11eb-87d4-ae54bffc7174.png)

The config is set as follows:
![image](https://user-images.githubusercontent.com/84389274/121012492-5945cd00-c7ca-11eb-88b6-c5e1d63eb2cb.png)

**Comment by anycodes** [comment]
Could you run the command : `cat s.yaml`，and show the content for me

**Comment by anycodes** [comment]
初步怀疑，`core`模块，没能在检测到组件密钥异常时，即使更新和获取。
