### ISSUE TITLE
fast start flask failed with account access setting

### ISSUE THREAD

**Issue by siyuniuali** [Serverless-Devs/Serverless-Devs#112]
self-check: NAS is set up and running. Shenzhen serverless function is also initialized beforehand. Use the same command as the tutorial at open AI explorer. Default credential is set up using the correct name.

Get the following errors:
![image](https://user-images.githubusercontent.com/84389274/121013957-066d1500-c7cc-11eb-9a59-792f226d197f.png)

seems like the error is due to a lack of ACR request credentials. Wondering where to set up these credentials.

**Comment by anycodes** [comment]
@git-qfzhang qianfeng，这里我看了一下貌似是资源的问题？是不是需要用户先开通ACR？

@siyuniuali hey, could you try open this website: `https://cr.console.aliyun.com/`, and open Alibaba cloud container mirror service（ACR）

**Comment by david990917** [comment]
@anycodes @siyuniuali 您好，我重复了这个 flask 部署，出现了相同的提示信息。

> service role should have ACR GetAuthorizationToken/GetRepoTag access when runtime is custom-container.

开通 ACR 服务（官网中文为容器镜像服务）后可以 s deploy 成功。

**Comment by david990917** [comment]
这个项目部署的成果和传统的项目部署不同。

部署成功后，在 阿里云 函数计算页面，无法正常显示代码以及使用网页给定的URL链接进进行访问。
访问方式是直接使用部署成功时，命令行提示的链接进行访问。访问结果如下图：

![image](https://user-images.githubusercontent.com/37998674/121690193-1e100a80-caf8-11eb-864f-fc9795aa533b.png)
