### ISSUE TITLE
DK HTTP

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#121]

**Comment by hryang** [comment]
我是初学者，想用 s 体验 jmstack。按照提示使用 s 初始化 DK HTTP API 模板。然后执行 s deploy 时遇到如下问题：
<img width="899" alt="图片" src="https://user-images.githubusercontent.com/626967/121301317-94f7a880-c92a-11eb-914e-5dfbc03c47be.png">

然后走不下去了。我期望模板有对应的文档能告知正确的配置，典型错误处理。让初学者也能顺利的玩起来。

**Comment by xsahxl** [comment]
> 我是初学者，想用 s 体验 jmstack。按照提示使用 s 初始化 DK HTTP API 模板。然后执行 s deploy 时遇到如下问题：
> <img alt="图片" width="899" src="https://user-images.githubusercontent.com/626967/121301317-94f7a880-c92a-11eb-914e-5dfbc03c47be.png">
> 
> 然后走不下去了。我期望模板有对应的文档能告知正确的配置，典型错误处理。让初学者也能顺利的玩起来。

可以先检查下是否正确配置了密钥
- 获取密钥信息 s config get -l
- 设置密钥信息 s config add
- 选择 Alibaba Cloud (alibaba)
- AccountID：https://account.console.aliyun.com/v2/#/basic-info/index 可查看账号Id
- AccessKeyID和AccessKeySecret：https://ram.console.aliyun.com/manage/ak 点击 查看 Secret 可看到相关信息
- 最后输入alias， 在s.yml文件更改access为刚输入的alias
- 重新执行 s deploy

部署成功后，可以去fc控制台 https://fc.console.aliyun.com/ 查看自己部署的函数

**Comment by hryang** [comment]
弄明白了。这个问题是这样的：我配置了密钥，按照默认一路点回车，最后配置的账户信息是在 default 这个 alias 中。但是 s init 这个模板，s.yml 默认的alias是 alibaba.default ，所以我还是会遇到错误。建议做两个改进：
1. 可以提醒用户工具配置了哪些 alias，模版要求的账户 alias 是什么，有没有配置好。
2. 把 s config 设置的默认 alias 和模板 s.yml 中的默认 alias 统一起来。

**Comment by heimanba** [comment]
在这个示例中s.yml没有默认的alias哈，需要去选择alias, 这里的alias其实来自于 s config中的设置的。
![image](https://user-images.githubusercontent.com/5129967/121331281-4d344980-c949-11eb-8582-96b0ee794dca.png)

**Comment by anycodes** [comment]
这个问题的解决方案：在初始化项目的时候要求用户选择密钥信息。
