### ISSUE TITLE
s init 在选择模版时显示有问题

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#124]
**Describe the bug**
s init 进入 alibaba 的模板选择列表时，由于模板众多，没有办法在 terminal 区域完全显示。如下图所示，当 terminal 区域较小时，光标对应的模板没有在 terminal 中显示。

**Screenshots**
![image](https://user-images.githubusercontent.com/626967/121330879-f9c1fb80-c948-11eb-8693-535cfaac27c8.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Version [Big Sur]

**Additional context**

**Comment by anycodes** [comment]
此Bug已经修复。等待`2.0.51`发版。

修复方案：

在窗口高度足够的时候，显示内容为全部：
![image](https://user-images.githubusercontent.com/21079031/121347198-7ceb4d80-c959-11eb-8ece-a313101241b2.png)

这种显示，相对美观，且分类清晰

在窗口高度不足时，显示缩略内容：
![image](https://user-images.githubusercontent.com/21079031/121347290-98565880-c959-11eb-89d5-6d8983518141.png)

此时可以保证选择的光标始终在屏幕中。

**Comment by david990917** [comment]
目前显示的问题已经解决，但是在选择完成后，向上重塑配置过程的时候，会出现以下情况：
![image](https://user-images.githubusercontent.com/37998674/121690661-b4dcc700-caf8-11eb-8efb-a6f24c70661d.png)
猜想这个现象是由于滚动产生的。感觉可以进行进一步优化，使之实现的效果更美观。
