### ISSUE TITLE
MacOS会出现权限问题

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#126]
**Describe the bug**
MacOS会出现权限问题，在执行s init等指令的时候

**Screenshots**
![image](https://user-images.githubusercontent.com/21079031/122086340-32c10b00-ce36-11eb-83ea-68a5d5070eb4.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 2.0.36

**Additional context**

**Comment by anycodes** [comment]
在Mac操作系统下出现权限问题，可能是node_module目录的权限问题导致的。此时可以考虑：
```
sudo chmod -R 777 ${nodejs node module path}
sudo chown -R $USER ${nodejs node module path}
```

> 可以尝试替换` ${nodejs node module path}`为`user/local/lib/node_module`，例如：
> 
> ```
> sudo chmod -R 777 user/local/lib/node_module
> sudo chown -R $USER user/local/lib/node_module
> ```

除了上述问题，可以通过该放下解决，下属问题也可以尝试该方法：

![image](https://user-images.githubusercontent.com/21079031/122085448-4d46b480-ce35-11eb-91d2-c05cb88291ed.png)

**Comment by anycodes** [comment]
如果系统出现类似以下的错误：

![image](https://user-images.githubusercontent.com/21079031/122092569-a8c87080-ce3c-11eb-8cd0-15898e945439.png)

可以考虑通过以下指令解决：

```
sudo chmod -R 777 ~/.s/
```

**Comment by anycodes** [comment]
@heimanba  大佬，这一部分你看一下，如果在新的项目中，如果不会出现这个问题，可以帮忙点一下`unpin issue`

**Comment by heimanba** [comment]
已经解决了，其实理论上window也不必出现这样的问题了。不需要在管理员的模式下运行，在powershell 模式下执行也是ok 的
