### ISSUE TITLE
目前显示的问题已经解决，但是在选择完成后，向上重塑配置过程的时候，会出现以下情况：

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#127]
目前显示的问题已经解决，但是在选择完成后，向上重塑配置过程的时候，会出现以下情况：
![image](https://user-images.githubusercontent.com/37998674/121690661-b4dcc700-caf8-11eb-8efb-a6f24c70661d.png)
猜想这个现象是由于滚动产生的。感觉可以进行进一步优化，使之实现的效果更美观。

_Originally posted by @david990917 in https://github.com/Serverless-Devs/Serverless-Devs/issues/124#issuecomment-859568152_

**Comment by hryang** [comment]
在 2.0.5 版本上，s init 仍然有显示问题。在 terminal 显示非常狭窄时，s init 的前面的内容显示不出来，而且光标仍然在 terminal之外。

![image](https://user-images.githubusercontent.com/626967/121857398-29e21380-cd28-11eb-8e3e-03f1b91204a3.png)

**Comment by anycodes** [comment]
> 在 2.0.5 版本上，s init 仍然有显示问题。在 terminal 显示非常狭窄时，s init 的前面的内容显示不出来，而且光标仍然在 terminal之外。
> 
> ![image](https://user-images.githubusercontent.com/626967/121857398-29e21380-cd28-11eb-8e3e-03f1b91204a3.png)

初步判断，这应该是vscode的terminal的问题，这个需要研究一下做特殊兼容

**Comment by heimanba** [comment]
关于光标的问题，是inquirer的bug,需要调研下常用的cli是如何处理这样的情况
