### ISSUE TITLE
s cli logs 显示的报错信息难于理解，初学者不知道该如何修复

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#128]
执行 s cli logs，显示如下错误信息。该信息和其他命令，比如 `s cli lot`，的错误信息不一样，难于理解，不知道该如何修复。
![image](https://user-images.githubusercontent.com/626967/121858122-de7c3500-cd28-11eb-89c5-5884b3784872.png)

**Comment by anycodes** [comment]
针对部分组件指令进行了修复
![image](https://user-images.githubusercontent.com/21079031/122537994-b3f7e800-d058-11eb-9d50-6a62115b3e1a.png)
![image](https://user-images.githubusercontent.com/21079031/122538029-bc502300-d058-11eb-856d-b3b02487e2b6.png)
