### ISSUE TITLE
安装最后一步报错

### ISSUE THREAD

**Issue by cxbb666** [Serverless-Devs/Serverless-Devs#154]
![image](https://user-images.githubusercontent.com/53455264/127453061-dc94f01b-9754-4dd3-94a5-5ddaa2130e20.png)

**Comment by Stmlker** [comment]
yes,i do.

**Comment by anycodes** [comment]
这个问题很清晰和很明确的，大家应该是参加阿里云的小游戏机的体验活动遇到的问题。

![image](https://user-images.githubusercontent.com/21079031/127584374-5787c65c-124f-42e8-a4fe-cf38fc60340b.png)

这个问题是，大家并没有开通函数计算，就要部署业务在函数计算上，所以会提醒大家服务不可用。这个和工具是无关的。

推荐大家在做某些体验活动的时候，按照顺序来进行。
