### ISSUE TITLE
运行s deploy这个后报错

### ISSUE THREAD

**Issue by Stmlker** [Serverless-Devs/Serverless-Devs#155]
在阿里云上5. 搭建掌上游戏机项目 执行第5 步后，也就是运行s deploy这个后报错，报错截图如下
<img width="601" alt="2021-07-29_194414" src="https://user-images.githubusercontent.com/46089222/127488284-94d06a31-1780-4024-a9d0-7f3c64b9b5f7.png">

**Comment by SSJLYY** [comment]
+1

**Comment by SunJiFengPlus** [comment]
俺也一样

**Comment by SunJiFengPlus** [comment]
我使用以前创建的 accessId 和 accessKey 的时候会遇到这种情况, 我新建了一个 accessId 和 accessKey 好使. 
- 把之前创建的 config 删掉 ```s config delete -a default```
- 重新添加配置 ```s config add```

**Comment by anycodes** [comment]
这个bug理论是解决了的。目前可以在验证一下。
