### ISSUE TITLE
s 日志输出时，日志等级多了一个空格

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#156]
执行 s deploy，显示下面的日志输出：
<img width="733" alt="图片" src="https://user-images.githubusercontent.com/626967/128277887-c717e133-6f0c-446f-9d66-21d06581e8a8.png">

其中 [INFO ] 中 “O” 和 “]“ 之间多了一个空格，应该是 [INFO]。

**Comment by anycodes** [comment]
这一部分将会进行统一升级，可以参考：https://github.com/Serverless-Devs/Serverless-Devs/discussions/176

**Comment by heimanba** [comment]
在  #220 会优化此需求
