### ISSUE TITLE
Mac 版 Serverless Desktop 因为无法验证开发者而无法安装

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#158]
在 mac 上安装 Serverless Desktop，提示无法验证开发者。

<img width="260" alt="图片" src="https://user-images.githubusercontent.com/626967/128303574-a2ecb4fd-9fc2-47da-8062-0a0fbf01230e.png">

很多 mac 用户走到这一步估计就会放弃。

**Comment by hanxie-crypto** [comment]
我后面申请一个苹果开发者证书
