### ISSUE TITLE
使用 desktop 中创建删除应用时，有可能误删整个目录的数据

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#161]
1. 如下图所示，创建应用。此时如果选择一个非空目录，也是可以成功的。比如该项目的根目录在 icloud 下
<img width="1350" alt="图片" src="https://user-images.githubusercontent.com/626967/128308100-e5363433-9a02-40cd-ae93-aaeb3437dc1f.png">
2. 如下图所示，删除应用。此时该目录下的所有数据都会删除 
<img width="741" alt="图片" src="https://user-images.githubusercontent.com/626967/128309045-6a22f2ec-e039-43b8-a633-8ea2e63499ad.png">

这里我觉得比较合理，安全的做法是：
1. 创建应用时，每次创建一个新目录，用应用名作为目录名。如果遇到了重名，就添加 _1 之类的后缀
2. 删除目录时，提醒用户当前路径下的所有数据都会删除（路径名一定要显示出来！），用户来确认。

**Comment by hanxie-crypto** [comment]
已修复，可以直接从官网下载最新版本，或者本地 通过topbar上的 红色提示更新应用。 优化增加了针对已有文件的目录自动创建项目名的目录，如果重复往后累加_1 ， 如果是空目录则以空目录为根目录
![reset2](https://user-images.githubusercontent.com/4457084/130039334-4a7c08d8-1f20-4795-ac8a-b8fa5df238e5.gif)
