### ISSUE TITLE
应用管理 UI 交互优化

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#168]
如下图所示，大家看看下面的交互逻辑是否合理。
1. 点击应用卡片的任何地方都能进入应用详情页。当前的行为是必须点击应用详情才可以进入。
2. 建议取消“应用详情”，“应用配置“，”快捷操作“ 几个按钮。我安装一个应用后，很自然的是想开始调试。我看到这几个按钮后，直觉认为调试在别处，但是调试功能其实在应用详情页。开发者很难联想到端云连调功能是在应用详情页中。还不如删除这几个按钮，开发者会下意识的点击应用卡片，就会看到所有的操作了。
<img width="637" alt="图片" src="https://user-images.githubusercontent.com/626967/128627678-0388ba18-a333-4b15-a2ab-187b5a6372d5.png">

**Comment by hanxie-crypto** [comment]
已修复，点击卡片直接进入项目详情， 并且增加了 通过卡片列表访问文件的功能
