### ISSUE TITLE
希望 s 发布了新版本， 还应该主动让用户知道， 并且告诉用户升级的命令， 如 fun 一样

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#171]
![image](https://user-images.githubusercontent.com/10919599/128993942-0eb6841b-f231-45bb-aaab-1a29a7ff2edd.png)

希望 s 发布了新版本， 还应该主动让用户知道， 并且告诉用户升级的命令， 如 fun 一样

**Comment by anycodes** [comment]
这个功能是可以加的

**Comment by heimanba** [comment]
已经修复s 版本 >= 2.0.81
