### ISSUE TITLE
desktop 的配置编辑中 ctrl-z 撤销功能有时不可用

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#172]
在 desktop 的配置编辑中，当我删除配置中的内容，想要通过 ctrl-z 撤销删除时，很多时候是不可用的，导致用户的内容无法恢复。猜测和自动保存功能有关。

![image](https://user-images.githubusercontent.com/626967/129383475-f50191f9-c38b-4b4b-a8c0-a44bcfecaf07.png)

**Comment by hanxie-crypto** [comment]
![image](https://user-images.githubusercontent.com/4457084/130037795-6c484530-69d9-4f28-a789-4eed7a0a65b1.png) 更新一下最新版本，做了一个优化，右边编辑器的编辑和保存做了分离， 只有用户确定后 通过快捷键 command+s （windows 是 ctrl+s） 来保存更新，这样会避免误操作，删除后也可以随时撤回

**Comment by hanxie-crypto** [comment]
![image](https://user-images.githubusercontent.com/4457084/130038633-6df10c15-f20d-49b4-b502-6a4aa780c521.png)
另外增加了左右滑栏可以调节可视化和配置部分的视口
