### ISSUE TITLE
Windows下s --version或者-v无显示

### ISSUE THREAD

**Issue by raykie** [Serverless-Devs/Serverless-Devs#174]
**截图**
![image](https://user-images.githubusercontent.com/51851458/130058342-d6818eac-6e46-45c5-81d7-a418d2dc0e00.png)

**Comment by heimanba** [comment]
每次执行 s --version 会去请求 npm最新版本。和S更新一起解决 [#171](https://github.com/Serverless-Devs/Serverless-Devs/issues/171)
