### ISSUE TITLE
默认升级策略

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#188]
由于s工具是安装在客户本地，我们在修复一些重要的版本，无法通知到用户。这里需要默认升级策略

#### 强制更新的策略为:
1. 通过`update-notifier`中的版本和当前版本进行对比
2. 根据`semver`(2[major].1[minor].3[patch]) 版本号策略，比如使用`semver-diff`模块进行更新。具体为
 - 如果有**minor**或者**major**版本的更新，一定要更新

#### 强制更新的具体实现
1. 在update-notifier的更新操作返回时候进行检查
1. 找到当前devs工具的全局位置,通过命令 `npm config get prefix`获取。
> 注意通过`yarn`安装，`pnpm`安装，以及`shell`安装路径区别
2. 通过daemon 进程进行下载

**Comment by anycodes** [comment]
强制更新我是支持的，但是我担心的是兼容性问题。

**Comment by heimanba** [comment]
因为core 每次下载的都是最新的版本，所以理论上S需要对应着新的版本。
还需要在发布上有些规范，每次发布的时候都必须在 **patch** 的小版本待上一段时间

**Comment by heimanba** [comment]
已经发布
