### ISSUE TITLE
应用中心模板卡片交互反直觉

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#191]
如下图所示，鼠标放到模板卡片上，是“点击”的手势，但实际上只有点击红框中的链接才可以进入，其他地方都没有反应。符合直觉的行为应该是点击卡片任何地方都可以进入详情页吧。
![图片](https://user-images.githubusercontent.com/626967/132429891-1e4d8e4f-9b29-4df5-a1d2-332540120c84.png)

**Comment by hanxie-crypto** [comment]
修复完成
