### ISSUE TITLE
应用模板操作名不统一

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#192]
在这个界面下是“使用”
![图片](https://user-images.githubusercontent.com/626967/132430404-c763744a-7c69-4d60-a7d5-239febdc814a.png)

在里面的界面下，是“下载”
![图片](https://user-images.githubusercontent.com/626967/132430444-0b56db76-581d-4b3b-8f7c-b235f461a4a5.png)

应该使用统一的描述。

**Comment by hanxie-crypto** [comment]
统一修复为下载
