### ISSUE TITLE
thinkphp 模板的在线体验走不通

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#194]
如下图所示，点击“在线体验”
![图片](https://user-images.githubusercontent.com/626967/132431396-9b90535c-83cb-4c96-9197-5f5806d530cb.png)

实际没有 thinkphp 的文档
![图片](https://user-images.githubusercontent.com/626967/132431446-2bfec6f8-96a0-45ca-a7ac-99fbbdfcf1bc.png)

另外，这里在线体验难道不是 clone thinkphp 模板仓库，然后用户直接根据命令来操作？现在的行为是下一堆文档，让用户自己去找相关的教程文档。在shell界面里，几个用户知道用 vim 或者 cat 把文档内容打开来看？这个体验不好。

**Comment by anycodes** [comment]
可以参考这个：https://github.com/devsapp/start-web-framework/tree/master/web-framework/php/thinkphp/src
