### ISSUE TITLE
Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by ruizefirst** [Serverless-Devs/Serverless-Devs#198]
s init docsite-basic
  ..
  ..
 s bugscheme deploy

[2021-09-15T09:51:58.105] [ERROR] [S-CLI] - Project jamstack-website failed to execute:

   Message:  Cannot read property 'success' of undefined
   You can get help for this component by [s jamstack-website -h]
   If you have questions, please tell us: https://github.com/Serverless-Devs/Serverless-Devs/issues

**Comment by hanxie-crypto** [comment]
这里是没有添加秘钥信息，可以通过s config add 增加一下，[秘钥获取地址](http://www.serverless-devs.com/docs/provider-config/alibabacloud)，最后秘钥别名填一下defaut 就行，加好秘钥信息后就可以在项目下执行s deploy拉

**Comment by anycodes** [comment]
@heimanba 这个报错是不是需要优化？

**Comment by heimanba** [comment]
@anycodes 这个报错已经到组件内部了，但是这个新版本已经不会出现此问题，版本在 2.0.84之后的
