### ISSUE TITLE
我如果没有配置密钥信息，使用的时候会报错

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#201]
**Describe the bug**

我如果没有配置密钥信息，使用的时候会提醒我是否创建，我选择了创建之后，提醒我错误。

**Screenshots**

![image](https://user-images.githubusercontent.com/21079031/134610187-6b740d94-2d39-4b47-a4c3-40408d0e1c8f.png)

**Desktop (please complete the following information):**
 - OS: centos
 - Version: @serverless-devs/s: 2.0.83, linux-x64, node-v12.4.0

**Additional context**
体验平台：https://developer.aliyun.com/adc/scenario/exp/ebbd2f5e145941a69c4e21e03e0d5eeb

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/commit/bf0ab70d73ac7d75865c032ee83b13823de6bf83
