### ISSUE TITLE
errorStack 信息不准确

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#205]
sls日志信息不全
```
errorStack:TypeError: e[t] is not a function
```
![image](https://user-images.githubusercontent.com/5129967/134810098-94963852-3fca-444b-8fca-1f52f927baf4.png)

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/commit/9fe6d8fb2703a9fcf8848033159b035b116a477d
