### ISSUE TITLE
增加清理动作指令

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#206]
s clean   => 等于删除 cache

s clean --component devsapp/fc  删除fc组件 (参数必填) 
s clean --cache core  删除cache下面的的某个文件(参数必填)

**Comment by heimanba** [comment]
兼容下 github源

**Comment by heimanba** [comment]
出错提示的时候

You can Run 's clean' to prune Serverless devs
And Run again with the '--debug' option or 's -h' to get more logs.

**Comment by heimanba** [comment]
s clean --all (删除 除了 access.yaml 的所有文件)

**Comment by heimanba** [comment]
s clean  直接使用报错，参数必填

**Comment by xsahxl** [comment]
综述：
- s clean 与 s clean -h行为一致
- s clean --all 删除~/.s下的所有文件（除了access.yaml和set-config.yml两个文件）
- s clean --component devsapp/fc 删除fc组件 (参数必填)
- s clean --cache core 删除cache下面的的某个文件(参数必填)
