### ISSUE TITLE
s 在 linux 下普通用户的体验问题

### ISSUE THREAD

**Issue by hryang** [Serverless-Devs/Serverless-Devs#212]
Linux 用户一般不会使用 root，通常是使用普通账户，然后为该账户赋予 sudo 权限。普通账户执行命令，以及以 sudo 权限执行命令，行为是有一些差异的。在 s 上，会带来以下一些体验问题：

1. 普通账户执行 `s init` 初始化项目，第一次执行时会让用户配置账户，AK相关信息，生成 access config。
2. 普通账户在 Linux 环境中执行 docker 相关的命令时，必须以 sudo 方式执行。此时 s 会提醒找不到 access config。

执行 `sudo s config add` 命令，以 sudo 方式添加账户、AK信息后，s 后续指令执行成功。因此，看起来普通账户在以 sudo 和 非 sudo 模式执行时，相关的配置信息不能共享。Linux 下的用户 100% 会遇到上述的体验问题。

**Comment by heimanba** [comment]
我来跟下这个问题哈
