### ISSUE TITLE
下载等进程卡死问题梳理

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#246]
- Logger不输出到本地文件
- postinstall 常用组件补齐
 ```
fc-api => 注意这个肯定不不是 devsapp/fc-api
 ```
- fs.unlink 是否能换成 rimraf
- https://help.aliyun.com/document_detail/153697.html

**Comment by xsahxl** [comment]
Logger不输出到本地文件 fix: https://github.com/Serverless-Devs/core/commit/bc0b30cf96503ef1e97da9ff9d35baac68fe4adf
