### ISSUE TITLE
云效自带的Serverless-Devs版本比较老，没有集成云效CICD的最佳实践

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#262]

**Comment by DevDengChao** [comment]
=-=?

**Comment by anycodes** [comment]
> =-=?

云效默认的版本大概率不会更新了，之后统一参考：https://docs.serverless-devs.com/serverless-devs/cicd#%E4%B8%8E%E4%BA%91%E6%95%88%E7%9A%84%E9%9B%86%E6%88%90

自己安装devs

**Comment by DevDengChao** [comment]
明白了, 这样手动安装 s 再进行配置的话其实跟直接用 NodeJS 步骤没什么差别了 🤣
