### ISSUE TITLE
access支持设置region

### ISSUE THREAD

**Issue by lowkeyrd** [Serverless-Devs/Serverless-Devs#270]
现在access只能配置account、ak/sk，但是provider config都是要增加region的，我们现在将region设置到prop里，很不友好。将region设置到access中，可以很方便的将测试、生产环境的profile放到不同的access中，对于ci/cd也更加友好

**Comment by lowkeyrd** [comment]
> 1. access是一个全局的配置，region放在access语义也不太妥当。region一般是跟随项目来的。可以这样做哈
> 
> ```
> edition: 1.0.0
> access: 'default'
> vars:
>   region: cn-hangzhou
> 
> services:
>   website-starter:
>     component: apigateway
>     props:
>       bucket: 'aidankun'
>       src:
>         publishDir: ./src
>         index: index.html
>       region: ${vars.region}
>       hosts:
>         - host: auto
> ```
> 
> 1. 在CICD的场景，区分环境是一个比较重要的场景。一般会这样使用，比如默认的开发环境是` s.yaml`,线上环境配置为`s-pro.yaml` 。在执行CD时候这样使用`s deploy -t ./s-pro.yaml`

region跟ak/sk一样，是provider的必备属性，access里有region，就相当于一个完整的ProviderConfig了。我认为region是不适合用var来表示的，var的用途是用户自定义属性，而region是系统认识的关键字
我的建议是：
1. s.yaml支持显示描述access，组件需要用到region的地方都可以从access里拿到。比如
edition: 1.0.0
access: 'default'
access:
  region: cn-hangzhou
  accessKeyId: xxxx
  securityKeyId: xxx

services:
  website-starter:
    ...

2. access文件里支持region，优先使用s.yaml中声明的，否则使用access文件中的

**Comment by heimanba** [comment]
第一点有个问题，就是`s.yaml`一般用户不会ignore掉。会不会将ak,sk放在s.yaml配置中，容易泄露用户的ak,sk哈

第二点： fun 工具其实就这么干的，可以看下的

**Comment by anycodes** [comment]
这里面的region作为全局变量其实并不是非常合理，目前在fun上面封装的midway，以及Serverless Framework，都是将region单独拿出来的，而不是配置到系统中。因为这里涉及到Region可能在同一应用中，有不同表现，例如前端我部署到A区，后端在A区没开，那么就要部署到B区；另外，在开发过程中，region可能是一个频繁切换的变量。

综上所述，我并不是非常推荐将region配置到系统中。但是如果想要，可以考虑把region放到环境变量中，可以指当作一种全局来用。

**Comment by lowkeyrd** [comment]
放到环境变量里是可以的，我的意思是region同ak/sk一样应该是系统的关键字，放到access中可以更方便用户进行cicd。因为测试、生产环境往往使用的是不同的子账号，所以连同region一起放到testing.access、production.access，使用不同的access就能进行环境级的隔离了。
我的proposal：
1. access增加region属性，默认传递到组件中
2. 如果env中指定了region，则覆盖access的
这样region可以结合access和env使用，满足多种场景

**Comment by anycodes** [comment]
这一部分我们可以找时间讨论一下。
