### ISSUE TITLE
删除 ~/.s/cache/core ，组件找core 挂掉了

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#273]
![image](https://user-images.githubusercontent.com/5129967/139397748-ddddc4db-67ac-4cc7-8ac4-ff6a0bac530e.png)

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/commit/a50d6be938d5eae787a0fd084120ac243dfa4e04
