### ISSUE TITLE
s config 命令

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#274]
文档地址 https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/command/config.md
### s config -h
![image](https://user-images.githubusercontent.com/5129967/139400469-4c4dab81-23e1-48bc-ab88-70abed762b58.png)

### config add
![image](https://user-images.githubusercontent.com/5129967/139400859-dca4bbed-0276-4a60-8ecf-e1c44a40b0ed.png)

### config get
![image](https://user-images.githubusercontent.com/5129967/139402209-d0d5c4db-295b-4c48-a649-5aa83a5cd2d1.png)

### -a变换
![image](https://user-images.githubusercontent.com/5129967/139402613-f2b88042-51ba-48f7-ae14-a3c329c2c02d.png)
` -a, --aliasName [name]` 全部换成 `-a, --access [aliasName] `

### config delete
删除结果展示
![image](https://user-images.githubusercontent.com/5129967/139407003-323fe6ee-14eb-4c49-bd88-9365e5659789.png)

**Comment by xsahxl** [comment]
s config add: https://github.com/Serverless-Devs/core/commit/416a81e93f5d69d8189e62615259107e3286a33f

**Comment by xsahxl** [comment]
https://github.com/Serverless-Devs/Serverless-Devs/commit/c42276012f11a3170fcf8c318d18ae54dd17bbc2
