### ISSUE TITLE
the documentation page for YAML spec is broken

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/Serverless-Devs#279]
the documentation page for YAML spec is broken:
https://github.com/Serverless-Devs/docs/blob/master/zh/yaml.md

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/139522317-493d42b1-8cd9-4046-abba-791bcac10aec.png)

Broken? There seems to be no problem here. Is it the factor of the network?

**Comment by anycodes** [comment]
By the way, there is a new document fort yaml spec: https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/yaml.md

(The latest version is similar to the previous version, but more perfect)

**Comment by newbaluku** [comment]
seems to have problem accessing from my side
<img width="1023" alt="404" src="https://user-images.githubusercontent.com/13480257/139536575-36550ef7-1e28-4674-a408-7ee3c0b831d9.png">

but this is ok:
https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/yaml.md

Thanks.

**Comment by newbaluku** [comment]
btw, I'm accessing outside of China.

**Comment by heimanba** [comment]
sorry to caused you trouble. We are urgently translating English

**Comment by newbaluku** [comment]
ok. no prob.

but would like to know the spec for the following as they are not defined in the ZH page.

logConfig
- currently setting it to `logConfig: auto` works, but would like to know what are the available options.

upload code via oss
- currently one of my project is larger than 50MB, may I know how to specify this in yml?

**Comment by anycodes** [comment]
I am sorry, the docs of 'https://github.com/Serverless-Devs/docs/blob/master/zh/yaml.md' was `private`. Now I will make it `public`

**Comment by newbaluku** [comment]
> ok. no prob.
> 
> but would like to know the spec for the following as they are not defined in the ZH page.
> 
> logConfig
> 
> * currently setting it to `logConfig: auto` works, but would like to know what are the available options.
> 
> upload code via oss
> 
> * currently one of my project is larger than 50MB, may I know how to specify this in yml?

ok, Thanks for the fix.

any help with these? because I couldn't find any doc on them so far.

**Comment by newbaluku** [comment]
any help?

**Comment by heimanba** [comment]
> > ok. no prob.
> > but would like to know the spec for the following as they are not defined in the ZH page.
> > logConfig
> > 
> > * currently setting it to `logConfig: auto` works, but would like to know what are the available options.
> > 
> > upload code via oss
> > 
> > * currently one of my project is larger than 50MB, may I know how to specify this in yml?
> 
> ok, Thanks for the fix.
> 
> any help with these? because I couldn't find any doc on them so far.

### logConfig 

https://github.com/devsapp/fc/blob/main/docs/Others/yaml.md

###  project is larger than 50MB ,please try this
https://github.com/awesome-fc/fc-faq/blob/main/docs/%E5%A4%A7%E4%BB%A3%E7%A0%81%E5%8C%85%E9%83%A8%E7%BD%B2%E7%9A%84%E5%AE%9E%E8%B7%B5%E6%A1%88%E4%BE%8B.md
