### ISSUE TITLE
部署后报错

### ISSUE THREAD

**Issue by congtargets** [Serverless-Devs/Serverless-Devs#282]
[2021-11-01T23:48:48.063] [INFO ] [FC-DEPLOY] - Using vpcConfig: auto: fc will try to generate related vpc resources automatically
✖ Project djangoBlog failed to execute:

TraceId:     00163e0658671635781728367
Environment: @serverless-devs/s: 2.0.92, @serverless-devs/core: 0.1.10, linux-x64, node-v12.4.0
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

ERROR:
FCAccessDeniedError: GET /account-settings failed with 403. requestid: 5d33e086-c5c6-49f8-a971-e14a1945dbd2, message: FC service is not enabled for current user..

Please copy traceId: 00163e0658671635781728367 and join Dingding group: 33947367 for consultation.
You can run 's clean --cache' to prune Serverless devs.
And run again with the '--debug' option or 's -h' to get more logs.

**Comment by heimanba** [comment]
没有开通函数计算控制台，麻烦开通下
https://fc.console.aliyun.com/

**Comment by congtargets** [comment]
谢谢
