### ISSUE TITLE
错误提示建议更友好

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#285]
https://github.com/devsapp/fc/issues/374
https://github.com/devsapp/fc/issues/395

现在有很多用户提出命令找不到，但是错误提示不太友好

**Comment by wss-git** [comment]
指令

**Comment by heimanba** [comment]
@anycode 麻烦提供下文案哈，这里两种典型的错误
1. 执行时候没有s.yaml， 这时候需要明确告诉用户
2. 当组件没有相关指令时候，比如执行 `s abc` 这时候也应该明确提醒客户。

这两种情况需要分别对应不同文案，麻烦大佬看下哈

**Comment by heimanba** [comment]
没有找到某个指令的时候
```
$ s deploy

ERROR:
TypeError: s.yaml格式不正确

请检查s.yaml的配置，Serverless Devs 的 Yaml 规范文档可以参考：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/yaml.md
```

**Comment by heimanba** [comment]
s.yaml 格式错误(无法JSON化)

整个工具无法使用

![image](https://user-images.githubusercontent.com/5129967/140679299-776ea6b5-b89b-47a4-b983-85f11416f987.png)

**Comment by heimanba** [comment]
## 技术
1. humanError
2. humanWarning(code: 0)

## 业务
1. s.yaml格式不正确（humanError） => code=1
2. s.yaml不存在, humanError => 1
3. 命令不存在, humanWarning => 0


所有的提示都加上 （文档链接）
