### ISSUE TITLE
log.task加上执行时间显示

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#289]
效果如下
```
✔ MyProject pre-action completed  (10s)
```

**Comment by heimanba** [comment]
可能需要提供一个完整的使用示例，否则用户不知道如何接入

**Comment by heimanba** [comment]
能达到上述的效果

https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/cli_design.md

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/commit/626abe9c73a648f731a5b708c6e7605b1387878f https://github.com/Serverless-Devs/core/commit/e554bb0d32c0ab60e78c282c095a43ff07d93956
