### ISSUE TITLE
建议允许用户使用环境变量自定义 `.s` 目录的位置

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#291]
**Is your feature request related to a problem? Please describe.**

由于云效流水线 Flow 不允许用户缓存 `/root/.s/components` 文件夹, 因此希望用户可以主动将 `/root/.s` 重定向到 `/root/.cache/.s` 以免在流水线运作期间反复下载相关组件.

聆听: 
+ [无法对 /root/.s/components 目录进行缓存](https://connect.console.aliyun.com/connect/detail/366255)
+ [建议将用户不能自定义基于绝对路径的缓存文件夹限制加入 Flow 的文档](https://connect.console.aliyun.com/connect/detail/368254)
+ [建议 @Serverless-Devs/s 可以基于环境变量控制 .s 文件夹生成的位置](https://connect.console.aliyun.com/connect/detail/368257)

**Describe the solution you'd like**

建议允许用户通过类似 `S_ROOT_HOME` 环境变量控制 `.s` 文件夹生成的路径.

**Describe alternatives you've considered**

或者给每个文件/文件夹都定义一个可选的环境变量? `S_COMPONENT_BASE_PATH` ... 
(太费功夫了, 还不如上一个简单易实现呢..)

**Additional context**

![image](https://user-images.githubusercontent.com/16363180/140505524-d891f10a-c7cd-4950-9062-44ad0764dadf.png)

**Comment by heimanba** [comment]
这里可能需要做几件事
1. 如果传递一个 S_HOME 的环境变量，则将 `.s` 存放在这里
2. 针对云效进行优化，如果是云效环境，并同时存在 `/root/.cache` 目录。则将`/root/.cache/.s`作为根目录
3. 可能还需要 针对其他的CICD的环境进行优化

**Comment by heimanba** [comment]
可以在 在Core层面编写一个共有的方法来处理这件事情，以后比如github ,gitlab等其他的假设可以内置的也可以统一做掉

**Comment by anycodes** [comment]
这个问题，可以在新的设计规范中进行一下处理，我下午给一反馈。感谢大家支持和建议

**Comment by anycodes** [comment]
https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/command/set.md#set-workspace-%E5%91%BD%E4%BB%A4

**Comment by anycodes** [comment]
> https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/command/set.md#set-workspace-%E5%91%BD%E4%BB%A4

@heimanba @DevDengChao @xsahxl 

这里增加了一个命令，可以进行devs的工作空间切换，但是要提醒用户，切换完成会导致配置的部分密钥信息等失效。

**Comment by DevDengChao** [comment]
> https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/command/set.md#set-workspace-%E5%91%BD%E4%BB%A4

@anycodes  这是个待实现的功能吧?

**Comment by anycodes** [comment]
> > https://github.com/Serverless-Devs/Serverless-Devs/blob/docs/docs/zh/command/set.md#set-workspace-%E5%91%BD%E4%BB%A4
> 
> @anycodes 这是个待实现的功能吧?

是的。

**Comment by xsahxl** [comment]
目前beta版本是支持此功能的：npm i @serverless-devs/s@beta -g，可以体验下哈。针对云效环境已经做了优化，默认缓存到 /root/.cache/.s

**Comment by DevDengChao** [comment]
> 针对云效环境已经做了优化

刚刚测试了一下， 发现 core 中的 getRootHome() 需要同时满足两个条件才会将 s home 修改到 `/root/.cache/.s`：
+ [x] 检查到 PIPELINE 开头的环境变量
+ [ ] 检查到 CLI_VERSION 环境变量， 并且值大于 `2.0.92` 

调试流水线中默认的环境变量发现缺少 CLI_VERSION 环境变量。

Ref:
+ PR: https://github.com/Serverless-Devs/core/pull/55
