### ISSUE TITLE
工具细节打磨

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#293]
### emoji 个文件之间加上空格(注意兼容性)
![image](https://user-images.githubusercontent.com/5129967/140595762-70f7d129-96a5-4c5a-97f8-92162d7f7ad3.png)

### 所有的链接都加上下划线，让用户知晓可以点击
![image](https://user-images.githubusercontent.com/5129967/140595808-a2c2763c-9d9b-4ef7-9ab6-e1452147c5ac.png)

### s config 指令
1. 在黑底效果不明显
![image](https://user-images.githubusercontent.com/5129967/140595833-19d25ed3-3b76-408e-b407-4b1098fe08a5.png)
2. `s config get` yaml显示美化(logger.output)
![image](https://user-images.githubusercontent.com/5129967/140595899-e0e30de8-8570-4956-a305-723cfc58f9e9.png)

### s component 
1. bug（显示了不存在的组件）(是不是看存在 publish.yaml 才算是组件哈)
![image](https://user-images.githubusercontent.com/5129967/140596015-0a64392d-f09b-4261-9641-8edae9b7eb03.png)
2. 假设输入一个不存在的组件，应该有所反馈
![image](https://user-images.githubusercontent.com/5129967/140596067-5f08aed8-9431-452c-8c89-29029620060a.png)
这里应该提示信息为: 不存在[xx]组件，请输入指令`s component` 查看所有的指令

### s set
1. 默认 `s set analysis`默认是`enable`状态的 
![image](https://user-images.githubusercontent.com/5129967/140596153-b2171290-ed94-4533-9ab9-eb794eda2974.png)

**Comment by anycodes** [comment]
bug（显示了不存在的组件）(是不是看存在 publish.yaml 才算是组件哈)：我觉得是的，需要有可以解析的publish.yaml，且type为Component才算

**Comment by anycodes** [comment]
关于s工具一些默认错误的梳理：

例如某个组件没有某个命令：
![image](https://user-images.githubusercontent.com/21079031/140676952-85721438-95f5-4402-8e62-e0dd8c96c06a.png)

现在给的是这样的错误，这个错误可以不对外透出，可以直接告诉是找不到命令，可以通过`s <serviceName> dede`等进行命令查看。

**Comment by anycodes** [comment]
像有一些默认报错，是不是可以规范统一，例如：
![image](https://user-images.githubusercontent.com/21079031/140677212-9a0ef891-7d93-48ce-824e-ba17d8d210b4.png)

此时是不是可以是：

```
$ s deploy

ERROR:
TypeError: s.yaml格式不正确

请检查s.yaml的配置
```

同时可以考虑给出相对应的帮助文档，例如：

```
$ s deploy

ERROR:
TypeError: s.yaml格式不正确

请检查s.yaml的配置，Serverless Devs 的 Yaml 规范文档可以参考：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/yaml.md
```

**Comment by anycodes** [comment]
在使用命令行的时候，当我Yaml配置错了密钥信息，他需要我反复确定多次，貌似是某个依赖的组件没有把密钥信息透传导致的，这个可能也要处理一下。

例如 s.yaml 的 service1 用了 fc 组件，那么 fc 组件获取一次密钥信息， fc 所以来的 fc-deploy 、fc-base 等都可以拿到上层组件的使用的密钥信息就好。

**Comment by anycodes** [comment]
当我Yaml格式错误之后，整个s工具都没办法使用，包括帮助文档等：
![image](https://user-images.githubusercontent.com/21079031/140677592-60042912-54e4-4f74-a435-24ad6d307d0c.png)

按照我的理解，这里只要不依赖yaml的功能理论可以使用。例如自带的命令:cli init config set等

**Comment by heimanba** [comment]
> 关于s工具一些默认错误的梳理：
> 
> 例如某个组件没有某个命令： ![image](https://user-images.githubusercontent.com/21079031/140676952-85721438-95f5-4402-8e62-e0dd8c96c06a.png)
> 
> 现在给的是这样的错误，这个错误可以不对外透出，可以直接告诉是找不到命令，可以通过`s <serviceName> dede`等进行命令查看。

这里新开issue梳理了 https://github.com/Serverless-Devs/Serverless-Devs/issues/285
