### ISSUE TITLE
deploy failed when project and logstore is specified in yml

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/Serverless-Devs#294]
If the above is included in the logConfig property, ie:

logConfig:
   project: my-logproject
   logstore: my-logstore

deploy would failed:

[2021-11-08T15:40:32.191] [INFO ] [FC-DEPLOY] - Checking Trigger httpTrigger exists
[2021-11-08T15:40:32.279] [INFO ] [FC-DEPLOY] - Trigger: httpTrigger already exists online.
[2021-11-08T15:40:32.285] [INFO ] [FC-DEPLOY] - Checking Trigger httpTrigger exists
✖ Make service my-dev...
[2021-11-08T15:40:32.460] [INFO ] [FC-DEPLOY] - Retrying fc: create , retry 1 time
✖ Make service my-dev...
[2021-11-08T15:40:33.527] [INFO ] [FC-DEPLOY] - Retrying fc: create , retry 2 time
✖ Make service my-dev...
[2021-11-08T15:40:36.030] [INFO ] [FC-DEPLOY] - Retrying fc: create , retry 3 time
✖ Project fc-my-dev-my-dev-app failed to execute:

TraceId:     88e9fe74fe3e1636357236033
Environment: @serverless-devs/s: 2.0.92, @serverless-devs/core: 0.1.10, darwin-x64, node-v14.16.1
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

ERROR:
FCInvalidArgumentError: POST /services failed with 400. requestid: 1f2ccc5b-bcbc-40a9-ad35-344167c83a83, message: project 'my-logproject' does not exist.

Please copy traceId: 88e9fe74fe3e1636357236033 and join Dingding group: 33947367 for consultation.
You can run 's clean --cache' to prune Serverless devs.
And run again with the '--debug' option or 's -h' to get more logs.

End of method: deploy

The logstore creation would succeed if I specify: logConfig: auto

**Comment by heimanba** [comment]
应该是您的 https://sls.console.aliyun.com/lognext/profile 的project `my-logproject`不存在。麻烦到sls的控制台确认下哈

**Comment by newbaluku** [comment]
I see. but shouldn't it be automatically created by the tool like in the case of the previous tool: fun ?

**Comment by heimanba** [comment]
https://github.com/devsapp/fc/blob/main/docs/Others/yaml.md#logConfig

you can add setting 
```
logConfig: auto 
```

**Comment by newbaluku** [comment]
ya, currently I'm already using this. I can live with this for now.

but submitting this issue here for your tracking and improvements. Because I felt this is a much better tool than funcraft to use.

Keep up the Good work guys. Thanks.

**Comment by heimanba** [comment]
好的好的，感谢您的建议。我记下您的优化建议哈

**Comment by heimanba** [comment]
这个问题在 https://github.com/devsapp/fc/issues/423 这里跟踪哈

**Comment by newbaluku** [comment]
Sure, Thanks.

I wonder if can also help to create 'project' if it is also specified but not currently exist.

**Comment by newbaluku** [comment]
however, these are Good-to-have features, not urgent as we could use 'auto' for now.

you can focus on more urgent and important features first. Thanks.
