### ISSUE TITLE
`s` 2.0.92 添加完账户后执行部署, 提示找不到 default 账户.

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#308]
**Describe the bug**
在 `Flow` 中使用 `s config add` 添加默认的阿里云账户后执行 `s deploy` 指令, 报错提示找不到 `default` 账户.

**Screenshots**
![lQLPDhrbllCkcwzNBcPNBZ2wUSsywsHZA_kBlQOwTsAMAA_1437_1475](https://user-images.githubusercontent.com/16363180/141248142-7a1b397e-3ef3-4b10-b771-64c76edb3c5b.png)

**Desktop (please complete the following information):**
 - Flow 北京构建集群

**Additional context**
尝试更新本地的包后重新触发 ci, 依然报错.

yarn.lock 中的相关包版本:
+ @serverless-devs/s: 2.0.92
+ @serverless-devs/core: 0.1.11

```yaml
"@serverless-devs/core@latest":
  version "0.1.11"
  resolved "https://registry.npmmirror.com/@serverless-devs/core/download/@serverless-devs/core-0.1.11.tgz#3c30152a3bd08f5b9fed85d39c12d7eba5b012bf"
  integrity sha512-S8xV/YgkrmCKElNZ1+BJ8YD3JX9BLRxV0Ir14WWs4SLWoLvhqCFy4fV+w2ljj9gO69/YhIaac81zxF4ljAuXTw==

"@serverless-devs/s@^2.0.92":
  version "2.0.92"
  resolved "https://registry.npmmirror.com/@serverless-devs/s/download/@serverless-devs/s-2.0.92.tgz#5a3c6b278a9f5394b0c2ef63532a9d53e836d5f7"
  integrity sha1-WjxrJ4qfU5Swwu9jUyqdU+g21fc=
  dependencies:
    "@serverless-devs/core" latest
```

**Comment by DevDengChao** [comment]
Flow 中追加 `-y` 和 `-a xxx` 参数到 `deploy` 指令后依然提示找不到指定的账户.

![image](https://user-images.githubusercontent.com/16363180/141251664-b265d8ea-73dd-49fb-97f6-e3a2a5087fac.png)

**Comment by DevDengChao** [comment]
但是本地执行类似的命令则可以成功部署

![R(QZ{P1TY`H 7`JVCBO}@2S](https://user-images.githubusercontent.com/16363180/141252884-6af0bccb-00cc-4c9c-b6de-7832884fd62c.png)

**Comment by heimanba** [comment]
大佬， 麻烦 先尝试下 `npm i @serverless-devs/s@beta -g` 哈

**Comment by DevDengChao** [comment]
> 大佬， 麻烦 先尝试下 `npm i @serverless-devs/s@beta -g` 哈

/ok

**Comment by DevDengChao** [comment]
用 `@serverless-devs/s@beta` 可以成功部署.
