### ISSUE TITLE
新版本s将支持用户自定义workspace, 组件用到os.homedir的地方需要换成core提供的getRootHome方法

### ISSUE THREAD

**Issue by xsahxl** [Serverless-Devs/Serverless-Devs#317]
比如fc-deploy组件用到cache目录

path.join(os.homedir(), '.s', 'cache', 'fc-deploy') 

替换成

path.join(core.getRootHome(), 'cache', 'fc-deploy')

**Comment by heimanba** [comment]
path.join(core.getRootHome() || os.homedir(), 'cache', 'fc-deploy')
