### ISSUE TITLE
如果在docker 环境， 默认加上 -y的特性

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#326]

**Comment by heimanba** [comment]
- 添加 access

**Comment by anycodes** [comment]
这个是不是不合理的？

**Comment by heimanba** [comment]
这个没有做哈，暂时不好实施，也不太好处理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月9日(周四) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Serverless-Devs/Serverless-Devs] 如果在docker 环境， 默认加上 -y的特性 (Issue #326)




 
这个是不是不合理的？
