### ISSUE TITLE
S yaml 命令讨论

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#330]
想在serverless devs里增加一个新的命令

s yaml

主要包括两个功能：

s yaml config: 打开一个网页，可以在线对Yaml进行编辑，有相关组件的超链接

s yaml check: 对Yaml格式进行判断，是否有问题

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/142586528-17b7626d-0ff2-4793-bef7-8900e750437a.png)

**Comment by hanxie-crypto** [comment]
命令行，桌面， 还有官网都带上这个功能，我觉得没什么问题。 不同入口，同一种服务

**Comment by lowkeyrd** [comment]
> 

s yaml config ==> s edit
s yaml check ==> s verify

理由：
1. 没必要增加yaml参数，直接用edit和verify表达更直接，除非之后打算提供json格式。另外如果要提供yaml和json两种模式，应该用s edit --output=yaml/json
2. 没必要单独check yaml格式，这个意义不大。s verify表示check 用户配置是否跟schema要求一致

**Comment by anycodes** [comment]
经过了一定的考虑，总结如下：


---------


# Desc 命令

`desc`命令是清理 Serverless Devs 的资源描述/行为描述文档的相关操作（例如`s.yaml`/`s.yml`等）。

- [命令解析](#命令解析)
- [desc edit 命令](#desc-edit-命令)
- [desc verify 命令](#desc-verify-命令)
    
## 命令解析

当我们执行`s desc -h`之后，可以进行相关帮助信息的查看：

```shell script
$ s desc -h
Usage: s desc [commands] [options]

Operate on application configuration.

📖 Document: https://github.com/Serverless-Devs/Serverless-Devs/tree/master/docs/zh/command/desc.md

Options:
  -h, --help  Display help for command

Commands:
  edit         📃 Visually edit resource/actions description documents
  verify      ✅ Verify the resource/actions description document
```

在该命令中，包括了两个个子命令：
- [edit：可视化编辑资源/行为描述文档](#desc-edit-命令)
- [verify：对资源/行为描述文档进行校验](#desc-verify-命令)

## desc edit 命令

通过该命令，可以对 Serverless Devs 的资源描述/行为描述文档进行可视化。 

执行`s desc edit -h`命令，可以看到帮助文档

```shell script
$ s desc edit -h

Usage: s desc edit

Visually edit resource/actions description documents

    Example:
        $ s desc edit

Options:
  -h, --help  Display help for command
```

执行完成该命令，系统会自动提供一个地址，形如：

```shell script
$ s desc edit

🌍 Please open the address in the browser for visual editing: http://127.0.0.1:5678
```

## desc verify 命令

通过该命令，可以对 Serverless Devs 的资源描述/行为描述文档进行校对，以及时发现描述的错误。 

执行`s desc verify -h`命令，可以看到帮助文档

```shell script
$ s desc verify -h

Usage: s desc verify

Verify the resource/actions description document

    Example:
        $ s desc verify

Options:
  -h, --help  Display help for command
```

执行完成该命令，系统会提醒用户资源描述的正确情况：

```shell script
$ s desc edit

# 正确结果： 

  ✅  Format verification passed.

# 错误结果： 
 ❌ Format verification failed.
      key               Your Value Type                 Target Type             Description
     CodeUri             String                                 Struct                    参数描述

# 输出魔法变量存在
 ✴️ Format validation unknown: 
     key               Your Value Type               Target Type           Description
     CodeUri             Unknown                          Struct                   参数描述

 ❓There may be dependencies between components, and you need to deploy them before you can determine the format.
```

**Comment by hryang** [comment]
为啥选择 desc 这个命令呢？desc 代表描述，不容易想到是和 yaml 有关。在英语里，yaml 精确的语义是 definition（定义），而不是 description（描述）。描述是一个非常宽泛的词，一般不会指形式化的定义。就像 function meta 中的 description 属性，或者 K8S pod 中的 description 属性，都是用来记录一段 human redable 的信息。所以用 desc 来描述 yaml 是不合适的。

我觉得封崇的那个建议是比较好的，s edit/verify，或者 s edit/validate，是更简洁，准确，直接的名称。

**Comment by anycodes** [comment]
> 为啥选择 desc 这个命令呢？desc 代表描述，不容易想到是和 yaml 有关。在我们的语境下，yaml 精确的语义是 definition（定义），而不是 description（描述）。描述是一个非常宽泛的词，一般不会指形式化的定义。就像 function meta 中的 description 属性，或者 K8S pod 中的 description 属性，都是用来记录一段 human redable 的信息。所以用 desc 来描述 yaml 是不合适的。
> 
> 我觉得封崇的那个建议是比较好的，s edit/verify，或者 s edit/validate，是更简洁，准确，直接的名称。


其实什么也不加，直接就是s edit/verify，确实是不错的，但是我考虑到的是命令收敛，因为之后，plan这些命令都会升到devs层面做，例如：

desc app：描述整个应用的情况，部署情况，本地的操作情况
desc edit：对资源描述/行为描述文件进行编辑，对应用编辑
desc verify：对资源描述/行为描述文件进行校验，对应用校验
desc plan：对应用更新/部署进行diff判定
.....

如果都是直接根命令的话，之后s下面的命令太多了，所以想着把它收敛到一个子命令下，这个子命令也在考虑是啥。

**Comment by anycodes** [comment]
这个命令改成app怎么样？

- s app desc：描述整个应用的情况，部署情况，本地的操作情况
- s app edit：对资源描述/行为描述文件进行编辑，对应用编辑
- s app verify：对资源描述/行为描述文件进行校验，对应用校验
- s app plan：对应用更新/部署进行diff判定

**Comment by heimanba** [comment]
这个命令应该是对s.yaml进行描述，用户使用 `-t`命令的时候，找不到s.yaml。是不是需要 指定 `-t`参数？

**Comment by anycodes** [comment]
![image](https://user-images.githubusercontent.com/21079031/144816042-92d93c9a-53f9-4ad9-8d94-c50772eae5fe.png)

**Comment by anycodes** [comment]
# App 命令

`app`命令是清理 Serverless Devs 的资源描述/行为描述文档的相关操作（例如`s.yaml`/`s.yml`等）。

- [命令解析](#命令解析)
- [app edit 命令](#app-edit-命令)
- [app verify 命令](#app-verify-命令)
    
## 命令解析

当我们执行`s app -h`之后，可以进行相关帮助信息的查看：

```shell script
$ s app -h
Usage: s app [commands] [options]

Operate on application configuration.

📖 Document: https://github.com/Serverless-Devs/Serverless-Devs/tree/master/docs/zh/command/app.md

Options:
  -h, --help  Display help for command
  -t, --template [templatePath]  Specify the template file

Commands:
  edit         📃 Visually edit resource/actions description documents
  verify      ✅ Verify the resource/actions description document
```

在该命令中，包括了两个个子命令：
- [edit：可视化编辑资源/行为描述文档](#app-edit-命令)
- [verify：对资源/行为描述文档进行校验](#app-verify-命令)

## app edit 命令

通过该命令，可以对 Serverless Devs 的资源描述/行为描述文档进行可视化。 

执行`s app edit -h`命令，可以看到帮助文档

```shell script
$ s desc edit -h

Usage: s app edit

Visually edit resource/actions description documents

    Example:
        $ s app edit

Options:
  -h, --help  Display help for command
  -t, --template [templatePath]  Specify the template file
```

执行完成该命令，系统会自动提供一个地址，形如：

```shell script
$ s app edit

🌍 Please open the address in the browser for visual editing: http://127.0.0.1:5678
```

## app verify 命令

通过该命令，可以对 Serverless Devs 的资源描述/行为描述文档进行校对，以及时发现描述的错误。 

执行`s desc app -h`命令，可以看到帮助文档

```shell script
$ s app verify -h

Usage: s app verify

Verify the resource/actions description document

    Example:
        $ s app verify

Options:
  -h, --help  Display help for command
  -t, --template [templatePath]  Specify the template file
```

执行完成该命令，系统会提醒用户资源描述的正确情况：

```shell script
$ s app verify

# 正确结果： 

  ✅  Format verification passed.

# 错误结果： 
 ❌ Format verification failed.
      key               Your Value Type                 Target Type             Description
     CodeUri             String                                 Struct                    参数描述

# 输出魔法变量存在
 ✴️ Format validation unknown: 
     key               Your Value Type               Target Type           Description
     CodeUri             Unknown                          Struct                   参数描述

 ❓There may be dependencies between components, and you need to deploy them before you can determine the format.
```
