### ISSUE TITLE
`s local invoke` 后容器不能顺利退出 Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#331]
**Describe the bug**

如题.

**Screenshots**

![image](https://user-images.githubusercontent.com/16363180/142994162-6b423cfa-50a3-4bc1-9faa-212b1b466ca4.png)

**Desktop (please complete the following information):**
 - s 2.0.94
 - FC Docker Custom Runtime 1.9.21

**Additional context**

样板工程: https://github.com/DevDengChao/aliyun-fc-issues/tree/master/fc-docker/custom-runtime/1.9.21/request-error-connection-refused

**Comment by DevDengChao** [comment]
Ref:
https://github.com/devsapp/fc/issues/472
https://github.com/devsapp/fc-local-invoke/pull/33

**Comment by git-qfzhang** [comment]
已经 fix ，待发布
