### ISSUE TITLE
`req.body` 的内容与预期不一致

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#332]
**Describe the bug**

在样板工程中执行 `s build && s local invoke -f request-body.json` 时, 控制台将提示 `req.body` 预期的内容为 `request-body.json` 中的内容, 但实际为空白 JSON 对象.

**Screenshots**

![image](https://user-images.githubusercontent.com/16363180/142995162-df0e35df-10b7-47f1-b0fd-3cc3f528b1f1.png)

**Desktop (please complete the following information):**
 - s 2.0.94，2.0.96
 - FC docker custom runtime 1.9.21

**Additional context**

样板工程: https://github.com/DevDengChao/aliyun-fc-issues/tree/master/fc-docker/custom-runtime/1.9.21/unexpected-request-body

**Comment by anycodes** [comment]
现在排查一下，稍等

**Comment by wss-git** [comment]
req.body 接受不到参数，可以试试通过这种方式接受

````
var rawData = "";
  req.on('data', function (chunk) {
      rawData += chunk;
  });
  req.on('end', function () {
      console.log(rawData);
      res.sendStatus(200);
  });
````

**Comment by wss-git** [comment]
或者这样写也是可以获取的

https://gitee.com/devsapp/start-fc/blob/main/custom-function/nodejs12/fc-custom-nodejs12-event/src/code/server.js#L8-10
