### ISSUE TITLE
建议添加 s.yaml 文件在多环境部署时的推荐文件名规范

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#333]
**Is your feature request related to a problem? Please describe.**

目前 s 仅支持当前目录下的 `s.yaml` 文件和 `s.yml` 文件，对于需要多环境部署的工程，可以通过新增 s 文件的数量，并在命令行通过 `-t` 参数指定文件名来进行调用。
但目前对用户自定义的文件名并没有任何的推荐、约束，导致后续无法基于文件名判断是否为 s 的多环境配置文件。

**Describe the solution you'd like**

可以参考 Spring 对 profile 文件的命名约定，例如 `application-dev.yaml` 即 `spring.profiles.active=dev` 时所使用的配置文件。
`s.yaml` 也可以约定类似 `s(-.*)?.ya?ml` 的推荐命名规范。

**Comment by heimanba** [comment]
感谢，非常有效的建议！！！
