### ISSUE TITLE
建议向 SchemaStore 注册 s.yaml 文件规范

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#334]
**Is your feature request related to a problem? Please describe.**

目前常见的 IDE 对 `s.yaml` 文件的编写缺少自动补全功能。但对于 `package.json` 文件，常见的 IDE 对其都有一定的自动补全功能。
以 IDEA 、WebStrom 为例， 调查后发现 IDE 利用 SchemaStore 提供的 json 协议对 `package.json` 文件提供了文档与自动补全功能。

![image](https://user-images.githubusercontent.com/16363180/143385541-2f50822b-14b6-4d6b-b41f-832f4a726095.png)

![image](https://user-images.githubusercontent.com/16363180/143376194-cb7181c1-2424-4f3b-a16f-1e4935aa4188.png)

**Describe the solution you'd like**

向 https://github.com/SchemaStore/schemastore/ 发起 PR，注册 s.yaml 文件规范。

**Additional context**

前置条件：
+ [x] #333

**Comment by heimanba** [comment]
这个问题已经规范在我们的vscode 插件里面实现。这个规范我们研究下哈。感谢大佬建议

**Comment by heimanba** [comment]
组件发布的标准将基于jsonSchema 进行开发，在V2版本规范将发布

**Comment by DevDengChao** [comment]
可以向 JSON Schema 仓库发起 PR ，将协议链接设置为自己仓库里的文件链接或其他公网链接.
这样可以避免每一次小规模更新协议标准都需要向 JSON Schema 发起 PR 的问题。

参考：
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L17-L24

**Comment by DevDengChao** [comment]
=-=? 请问是放弃实现这个规范文件了还是已经实现并发布了?

**Comment by anycodes** [comment]
> =-=? 请问是放弃实现这个规范文件了还是已经实现并发布了?

只有会在vscode插件上来直接做，目前vscode插件已经开始测试了：https://github.com/Serverless-Devs/serverless-devs-vscode-plugin

**Comment by DevDengChao** [comment]
好吧.
