### ISSUE TITLE
断网时候报错

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#341]
![image](https://user-images.githubusercontent.com/5129967/143800141-beed9114-ae18-49b0-8a4f-3a6b904b7e34.png)

**Comment by xsahxl** [comment]
![image](https://user-images.githubusercontent.com/21330840/144960949-ed42a9cd-7f2d-4f5e-890b-4a3f1e43e86c.png)
没网的时候getPid确实会返回unknown, 但traceId后面挂了个时间戳，也是唯一的。基本不影响的。
