### ISSUE TITLE
s deploy 的执行细节

### ISSUE THREAD

**Issue by g8up** [Serverless-Devs/Serverless-Devs#346]
**Describe the bug**
- `s -help` 回显中没有列出 `deploy` command
- 针对同一个本地工程，第二次执行 `s deploy` ，是会覆盖第一次的部署，还是跳过？回显中只是体现了各种`xxx exists`。
- readme 里也没有找到关于 deploy 的细节。

**Desktop (please complete the following information):**
```bash
shell@Alicloud:~$ s --version
@serverless-devs/s: 2.0.94, @serverless-devs/core: 0.1.14, linux-x64, node-v12.13.1
```

**Comment by anycodes** [comment]
当你`s -h`之后，是可以看到相关的帮助信息：
![image](https://user-images.githubusercontent.com/21079031/143847522-106ae35e-e127-4848-aff9-b1d6ea44b151.png)

此时可以根据你的需求，查看某个应用的帮助信息，例如：

![image](https://user-images.githubusercontent.com/21079031/143847588-06ea3c33-f49f-4a66-bad4-f3742e6c8af2.png)

可以根据这个应用的组件，看到这个应用具备的能力，并执行`-h`，例如：

![image](https://user-images.githubusercontent.com/21079031/143847661-ae53e670-055b-4235-8879-584d03d2cb9a.png)

也可以参考文档：
https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/command/deploy.md
