### ISSUE TITLE
s init 最新能力

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#348]
当执行`s init`之后：

```
🚀 Serverless Awesome: https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/awesome.md

? Hello Serverless for Cloud Vendors (Use arrow keys or type to search)
❯ Alibaba Cloud Serverless 
  AWS Cloud Serverless 
  Baidu Cloud Serverless 
  Huawei Cloud Serverless 
  Tencent Cloud Serverless 
  Dev Template for Serverless Devs 
```

其中：
`Huawei Cloud Serverless` ：https://github.com/xinwuyun/start-fg ，命令为`s init xinwuyun/start-fg`

关于`Alibaba Cloud Serverless `的变更：
- Quick start [Deploy function in 1 minutes]
    -  [HTTP] Node.js 12
    -  [HTTP] Python3
    -  [HTTP] Java8
    -  [HTTP] PHP7
    -  [HTTP] Go (custom)
    -  [HTTP] Typescript (custom)
    -  [HTTP] Ruby (custom)
    -  [HTTP] C++ (custom)
    -  [Event] Node.js 12
    -  [Event] Python3
    -  [Event] Java8
    -  [Event] PHP7
    -  [Event] Powershell (custom)
    -  [Event] Lua (custom)
    -  [Event] Rust (custom)
    -  [Event] Dart (custom)
- Container example [Deploy function with custom-container]
    - [HTTP] C++
    - [HTTP] Java (Springboot)
    - [HTTP] Asp.net Core
    - [Event] Node.js 14
    - [Event] Python3.9
    - [Event] C++
- Web Framework [Deploy a web framework]
    - Express.js
    - Egg.js
    - Koa.js
    - Nuxt.js (SSR)
    - Next.js (SSR)
    - Django
    - Flask
    - Tornado
    - Springboot
    - ThinkPHP
    - Laravel
- Static website [Deploy a static website]
   - Vue.js
   - React.js
   - Docusaurus
   - Hexo
   - Vuepress
- Best practice [Experience serverless project]
   - [AI] Pytorch
   - [AI] Tensorflow
   - [AI] Image Prediction
   - [DB] MySQL Example
   - [DB] MongoDB Example
   - [DB] Redis Example
   - Puppeteer Example
   - FFmpeg Example
   - Mall admin Example

**Comment by lowkeyrd** [comment]
LGTM

**Comment by anycodes** [comment]
- Quick start [Deploy function in 1 minutes]
    -  [HTTP] Node.js 12: `s init start-fc-http-nodejs12`
    -  [HTTP] Python3: `s init start-fc-http-python3`
    -  [HTTP] Java8: `s init start-fc-http-java8`
    -  [HTTP] PHP7: `s init start-fc-http-php7`
    -  [HTTP] C++ (custom): `s init fc-custom-cpp-http`
    -  [Event] Node.js 12: `s init start-fc-event-nodejs12`
    -  [Event] Python3: `s init start-fc-event-python3`
    -  [Event] Java8: `s init start-fc-event-java8`
    -  [Event] PHP7: `s init start-fc-event-php7`
    -  [Event] Go (custom): `s init fc-custom-golang-event`
    -  [Event] Powershell (custom): `s init fc-custom-powershell-event`
    -  [Event] Typescript (custom): `s init fc-custom-typescript-event`
    -  [Event] Lua (custom): `s init fc-custom-lua-event`
    -  [Event] Ruby (custom): `s init fc-custom-ruby-event`
    -  [Event] Rust (custom): `s init fc-custom-rust-event`
    -  [Event] Dart (custom): `s init fc-custom-dart-event`
- Container example [Deploy function with custom-container]
    - [HTTP] C++: `s init start-fc-custom-container-http-cpp`
    - [HTTP] Java (Springboot): `s init start-fc-custom-container-http-springboot`
    - [HTTP] ASP.NET Core: `s init start-fc-custom-container-http-aspdotnetcore`
    - [Event] Node.js 14: `start-fc-custom-container-event-nodejs14`
    - [Event] Python3.9: `start-fc-custom-container-event-python3.9`
    - [Event] C++: `start-fc-custom-container-event-cpp`
- Web Framework [Deploy a web framework]
    - Express.js: `s init start-express`
    - Egg.js: `s init start-egg`
    - Koa.js: `s init start-koa`
    - Nuxt.js (SSR): `s init start-nuxt-ssr`
    - Next.js (SSR): `s init start-next-ssr`
    - Django: `s init start-django`
    - Flask: `s init start-flask`
    - Tornado: `s init start-tornado`
    - Springboot: `s init start-springboot`
    - ThinkPHP: `s init start-thinkphp`
    - Laravel: `s init start-laravel`
- Static website [Deploy a static website]
   - Vue.js: `s init website-vue`
   - React.js: `s init website-react`
   - Docusaurus:  `s init website-docusaurus `
   - Hexo: `s init website-hexo`
   - Vuepress: `s init website-vuepress`
- Best practice [Experience serverless project]
   - [AI] Pytorch: `s init start-pytorch`
   - [AI] Tensorflow:  `s init start-tensorflow`
   - [AI] Image Prediction: `s init image-prediction-app`
   - [DB] MySQL Example: `s init start-fc-mysql-python`
   - [DB] MongoDB Example: `s init start-fc-mongodb-python`
   - [DB] Redis Example: `s init start-fc-redis-python`
   - Puppeteer Example: `s init puppeteer-nodejs`
   - FFmpeg Example: `s init ffmpeg-app`
   - Mall admin Example: `s init start-fc-mall-admin`

**Comment by anycodes** [comment]
注意，在cli的列表中，只需要显示前面的就好，例如

- Best practice [Experience serverless project]
   - [AI] Pytorch: `s init start-pytorch`
   - [AI] Tensorflow:  `s init start-tensorflow`
   - [AI] Image Prediction: `s init image-prediction-app`
   - [DB] MySQL Example: `s init start-fc-mysql-python`
   - [DB] MongoDB Example: `s init start-fc-mongodb-python`
   - [DB] Redis Example: `s init start-fc-redis-python`
   - Puppeteer Example: `s init puppeteer-nodejs`
   - FFmpeg Example: `s init ffmpeg-app`
   - Mall admin Example: `s init start-fc-mall-admin`

只需要显示：

- Best practice [Experience serverless project]
   - [AI] Pytorch
   - [AI] Tensorflow
   - [AI] Image Prediction
   - [DB] MySQL Example
   - [DB] MongoDB Example
   - [DB] Redis Example
   - Puppeteer Example
   - FFmpeg Example
   - Mall admin Example
