### ISSUE TITLE
s 2.0.96 local invoke 的容器退出后却不会终止当前进程

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#362]
**Describe the bug**
如题。
可以使用样本工程 https://github.com/DevDengChao/aliyun-fc-issues/tree/master/fc-docker/custom-runtime/1.9.21/unexpected-request-body 进行测试。

**Screenshots**

![image](https://user-images.githubusercontent.com/16363180/145583711-91630371-480d-4b21-bfe4-941e48b142f9.png)

**Additional context**

Microsoft Windows [Version 10.0.19044.1415]
WebStrom 2021.3.1 Preview
Docker version 20.10.11, build dea9396

**Comment by heimanba** [comment]
## fc相关组件的问题，在 devsapp/fc仓库中跟踪哈
https://github.com/devsapp/fc/issues/572
