### ISSUE TITLE
s  config add的时候如何直接指定不同云厂商

### ISSUE THREAD

**Issue by hehujun** [Serverless-Devs/Serverless-Devs#366]
s  config add的时候如何直接指定不同云厂商

**Comment by heimanba** [comment]
在 cli有交互式的引导。
![image](https://user-images.githubusercontent.com/5129967/146525035-59fc911a-b601-40f0-a21b-aff50ca44e9a.png)

**Comment by hehujun** [comment]
我想不用交互式，直接在config add的时候 通过一个参数 指定云厂商  可以吗？

**Comment by anycodes** [comment]
交互式只是一个快速途径，如果你想添加自定义的密钥信息，可以:
```
s config add --keyList key1,key2,key3 --valueList value1,value2,value3
```

**Comment by anycodes** [comment]
serverless devs的密钥，不和厂商绑定，只和别名绑定，你无论加什么格式的密钥都可以，你用的时候，我们就按照你加的格式，直接给组件使用。

例如你说你是私有云，有这几个密钥：abc、def，那么你就可以

```
s config add --keyList abc,def--valueList abcvalue/defvalue -a demo
```

你在使用的时候，直接用demo，就能拿到你配置的
```
{
"abc": "abcvalue",
"def": "defvalue"
}
```

**Comment by hehujun** [comment]
那我在部署的时候  根据component来区分 云厂商吗？

**Comment by hehujun** [comment]
1、s build --user-docker 方便说下原理是怎么回事吗？可以的话 我加个钉钉号  我的邮箱是hehujun@126.com

**Comment by hehujun** [comment]
2、s build的时候是只能根据默认的模板build，如果我的java项目不是maven管理的话，怎么处理呢 ？

**Comment by anycodes** [comment]
> 那我在部署的时候 根据component来区分 云厂商吗？

是的，例如你用了阿里云的fc的component，那就要用对应的密钥，所以你可以认为所有的功能都是component加载的，如果你用了华为云的，那就要使用华为云的component。

**Comment by anycodes** [comment]
> 1、s build --user-docker 方便说下原理是怎么回事吗？可以的话 我加个钉钉号 我的邮箱是[hehujun@126.com](mailto:hehujun@126.com)

如果你说的是fc组件，这个可以参考fc组件的build:https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/command/build.md#%E8%BF%9B%E9%98%B6%E6%93%8D%E4%BD%9C

**Comment by heimanba** [comment]
> 1、s build --user-docker 方便说下原理是怎么回事吗？可以的话 我加个钉钉号 我的邮箱是[hehujun@126.com](mailto:hehujun@126.com)

钉钉群号： 33947367
