### ISSUE TITLE
本地项目导入时弹窗文字看不到

### ISSUE THREAD

**Issue by virzs** [Serverless-Devs/Serverless-Devs#371]
**Describe the bug**

工作空间 导入本地项目 选择文件夹后，弹窗文字不可见

**Screenshots**
![image](https://user-images.githubusercontent.com/44538687/146698723-4bde9774-cf11-4f44-b7a6-2ca2d52f15df.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version Windows 11 21H2

**Comment by hanxie-crypto** [comment]
能贴一下文件的目录结构么，我来排查一下

**Comment by virzs** [comment]
我尝试了下，空文件夹也会出现这种情况，是不是没有检测到正确的项目时信息没有处理？

**Comment by hanxie-crypto** [comment]
新版本的destkop已经发布，可以尝试下载自信的版本
