### ISSUE TITLE
python项目s local start 指定配置文件的时候

### ISSUE THREAD

**Issue by hehujun** [Serverless-Devs/Serverless-Devs#374]
```
├── code
│   ├── index.py                             主代码
│   └── requirements.txt              第三方依赖
├── deploy
│   └── s.yaml                               s配置文件
└── venv                                      python虚拟环境
```
> 以上代码是从s init 下载的python3 http代码，s.yaml文件放到deploy目录就不行了，操作步骤如下
```
1、s build --use-docker -t deploy/s.yaml
虽然执行通过了，但是似乎直接跳过了源码目录
2、s local start -t deploy/s.yaml 
这步就直接报错了
```
> 我大概定位了一下问题，似乎是s.yaml中的codeUri: ./code配置的不对，但是修改成了../code或者./code还是执行失败，麻烦大佬帮忙看看是什么问题呢？

**Comment by heimanba** [comment]
这里是一个bug哈， 已经修复，预计明天能过发布正式版本。可以先临时将s.yml放在code 目录下面。直接使用 **s local start**  调试

**Comment by hehujun** [comment]
好的，java、node其它语言似乎也有这个问题

**Comment by heimanba** [comment]
> 好的，java、node其它语言似乎也有这个问题

是的哈，这个问题会统一解决的哈

**Comment by hehujun** [comment]
大佬，麻烦问下什么时候发布下个版本呢？

**Comment by xsahxl** [comment]
> 大佬，麻烦问下什么时候发布下个版本呢？

已经发布了，当时pr合并后就发布了哈
fix: https://github.com/devsapp/fc-local-invoke/pull/40/commits/3f3f8272787963b0a19a9fcb5d8b163ad516580a
