### ISSUE TITLE
【优化】配置 devsapp/fc和 fc时候会分别下载两次

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#379]
现在在 配置 devsapp/fc和 fc时候会分别下载两次。这里是否可以针对我们的特殊的组件做一些优化
比如:
loadComponent('fc') 默认变成 loadComponent('devsapp/fc')

### 限制条件
1. serverless源
2. 针对特定组件

### 特定组件
- fc-default
- fc

TODO:  s component 逻辑是否需要修改？

**Comment by xsahxl** [comment]
针对 serverless源 对所有组件 ：比如 loadComponent('fc') 默认变成 loadComponent('devsapp/fc')

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/commit/90a378fbff6120214f0e0103f0a0e1bd58eb4c91

**Comment by heimanba** [comment]
已完成优化，下载文件只会在缓存目录存在一份
