### ISSUE TITLE
【密钥】判断阿里云环境变量的密钥生效，同时存在AccessKeyID，  AccessKeySecret，  AccountId

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#385]

**Comment by wss-git** [comment]
可以参考：https://next.api.aliyun.com/api/Sts/2015-04-01/GetCallerIdentity?sdkStyle=old&params={}&lang=NODEJS&tab=DEMO

**Comment by xsahxl** [comment]
> 可以参考：[https://next.api.aliyun.com/api/Sts/2015-04-01/GetCallerIdentity?sdkStyle=old&params={}&lang=NODEJS&tab=DEMO](https://next.api.aliyun.com/api/Sts/2015-04-01/GetCallerIdentity?sdkStyle=old&params=%7B%7D&lang=NODEJS&tab=DEMO)

ok，后续关于密钥验证的问题会在此issue进行追踪
https://github.com/Serverless-Devs/Serverless-Devs/issues/375
