### ISSUE TITLE
生态规范兼容

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#388]
现在想要兼容更多生态的规范标准，例如K8S，例如Terraform等。目前的想法是增加生态命令：

```
s k8s *******
s terraform ******
```

欢迎讨论。

**Comment by lowkeyrd** [comment]
这个命令的行为预期是什么？

我理解的兼容生态，不是单纯的命令兼容，举两个例子：
1. 兼容K8s生态：是要把 S 进行K8s controller化，这样用户可以通过kubectl 直接apply 一个 S 的CR出去。用户交互的不再是s.yaml，而是一个K8s的CRD，基于GitOps + Kustomize能够很好的把这些yaml管理起来
2. 兼容Terraform生态：是用户上传一个Terraform的HCL文件或者指定一个Terraform Module源，S能够自动生成相应的组件，这样在 S 里可以直接通过Terraform来编排云资源，用于后续的操作

这两个生态是有一些差异的：
1. K8s的生态是围绕CRD建立的，可以很容易扩展出一个服务化的能力，所以融入K8s是要把S 变成一个Controller，用户用的是kubectl
2. Terraform的生态是围绕Terraform这个工具本身的，扩展的都是其Provider和Module，所以融入Terraform是要把其变成S的一个组件，用户用的还是S

**Comment by guyskk** [comment]
从 funcraft 过来的，其实 funcraft 用的挺好的，支持多云平台肯定是好事。我从用户的角度，觉得这些比较重要：
1. 稳定可靠：Serverless 本身不算成熟，作为生产工具必须把稳定可靠放在第一位，要帮用户把坑先填好，有坑的地方有提醒和可能的解决方案。
2. 抹平平台差异：如果不能抹平平台差异，就等于用户要为每个平台写一套配置，要去踩各个平台的坑。而且很显然不能直接把阿里ROS规范搬过来，否则别的平台不跟你玩，强行适配也会非常痛苦。
3. 关注业务场景，给业务带来更多价值，避免追求高大上、新奇的技术。例如冷启动时长，打包体积优化，如何支持更大的代码包，自动化部署，密钥管理，这些都是很需要解决的。
4. 没必要搞 k8s 和 Terraform，用 serverless 就是为了免运维，为了低成本的用阿里云腾讯云服务。把阿里云，腾讯云，AWS 做好、做完善就够了。如果公司有 k8s 运维，大家肯定就直接用 kubectl 了，何必再包一层 serveless 呢。

**Comment by anycodes** [comment]
> 从 funcraft 过来的，其实 funcraft 用的挺好的，支持多云平台肯定是好事。我从用户的角度，觉得这些比较重要：
> 
> 1. 稳定可靠：Serverless 本身不算成熟，作为生产工具必须把稳定可靠放在第一位，要帮用户把坑先填好，有坑的地方有提醒和可能的解决方案。
> 2. 抹平平台差异：如果不能抹平平台差异，就等于用户要为每个平台写一套配置，要去踩各个平台的坑。而且很显然不能直接把阿里ROS规范搬过来，否则别的平台不跟你玩，强行适配也会非常痛苦。
> 3. 关注业务场景，给业务带来更多价值，避免追求高大上、新奇的技术。例如冷启动时长，打包体积优化，如何支持更大的代码包，自动化部署，密钥管理，这些都是很需要解决的。
> 4. 没必要搞 k8s 和 Terraform，用 serverless 就是为了免运维，为了低成本的用阿里云腾讯云服务。把阿里云，腾讯云，AWS 做好、做完善就够了。如果公司有 k8s 运维，大家肯定就直接用 kubectl 了，何必再包一层 serveless 呢。

非常棒的意见。

**Comment by anycodes** [comment]
其实，我针对生态融合预期，并不是要包掉谁，集成谁，不想这样做。我不想侵入他们，我只想丰富他们。例如terraform生态，我就在想他是不是没有我们所说的build的能力，没有我们所提供的logs能力，也没有我们所提供的stress，探测，端云联调等能力？

那么我们是不是可以通过一个命令，识别出来terraform的项目，并且可以快速的通过s使用这些命令，例如，我在一个terraform项目下，直接用`s cli fc logs --region **** --service-name **** --function-name ****`，或者`s cli fc build --function ****`就可以进行相对应的“额外能力的使用”。这样算不算我们为生态做的加法？

当然，这个场景是我YY出来的，所以我说`想要兼容更多生态的规范标准，欢迎讨论`，具体如何设计，如何去做，还希望大家继续讨论，可能没有结果，没有结论，但是大家讨论的过程，可以让我大概了解自己的这个直觉是不是靠谱的，是不是有意义和价值的。
