### ISSUE TITLE
.s 缓存导致 s deploy 时偶尔出现只更新 service 不更新 function 的问题

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#391]
**Describe the bug**
RT

**Desktop (please complete the following information):**
s 2.0.92, 2.0.93-alpha.3, 2.0.93-beta.7, 2.0.96

**Additional context**
相关聆听： https://connect.console.aliyun.com/connect/detail/373945
相关工单： https://smartservice.console.aliyun.com/service/chat?id=0009L38CHD

**Comment by DevDengChao** [comment]
工单那边的工程师建议 deploy 前主动删除 .s 文件夹。
尝试这么操作后在 Flow 上运行了两次，暂时没有再次触发这个问题。

**Comment by heimanba** [comment]
这个问题之前执行两次 s build时候，出现硬连接失效。然后导致部署的是之前老的代码。已经完成修复。待观察查看是否还遇到此类问题
