### ISSUE TITLE
多平台同步发布与自动化发布

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#4]
Serverless Devs 目前已经正式对外发布，为了给用户提供更方便的选择，需要提供多种安装模式。

**Comment by anycodes** [comment]
安装模式：
- npm安装
- yarn安装
- brew安装
- apt安装
- yum安装
- 二进制安装

**Comment by rsonghuster** [comment]
二进制安装， 我希望的是 windows 用户是 install.exe 安装包那种， linux 和 mac 用户可以是一个 shell 脚本， 直接下载 fun 的binary 并且自动移动到 /usr/bin 目录下

**Comment by anycodes** [comment]
支持@rsonghuster的说法。但是我更希望二进制可以不再让大家关注npm，因为我觉得对我们来说二进制的很大的一个需求是非前端开发者，如果依旧感知npm，其实意义就不大了

**Comment by anycodes** [comment]
最新的安装：

- npm安装
- yarn安装
- apt安装
- yum安装
- 二进制安装
