### ISSUE TITLE
Changed in docker img from runtime-custom:build-1.9.21 to runtime-custom:build-1.10.1 breaks my deployment

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/Serverless-Devs#401]
I was using Serverless-Devs to deploy my Node.js project as a custom runtime to Aliyun FC. It was working fine when the tool build the function using image: registry.hub.docker.com/aliyunfc/runtime-custom:build-1.9.21

as such:

[S-CLI] - Start ...
[FC-BUILD] - Build artifact start...
[FC-BUILD] - Use docker for building.
[FC-BUILD] - Build function using image: registry.hub.docker.com/aliyunfc/runtime-custom:build-1.9.21
[FC-BUILD] - skip pulling image registry.hub.docker.com/aliyunfc/runtime-custom:build-1.9.21...
[FC-BUILD] - Build artifact successfully.
....
....

but something changed that yesterday when the tool somehow switches to use the image from: aliyunfc/runtime-custom:build-1.10.1

My function crashed on init with Error: Cannot find module './common/client/initOptions'

![image](https://user-images.githubusercontent.com/13480257/149899937-6523674f-3fad-4f88-9b86-e0373caa8d36.png)

Please advice how to switch back to use image: registry.hub.docker.com/aliyunfc/runtime-custom:build-1.9.21
for my build. Suspecting the latest version: aliyunfc/runtime-custom:build-1.10.1 has compatibility issues.

**My environments:**
Serverless-Devs: v2.0.98
Desktop: MacOS v11.3.1
Docker Desktop: v4.4.2
Nodejs:  v14.16.1

**Comment by rsonghuster** [comment]
export FC_DOCKER_VERSION=1.9.21

Temporarily deal with this first

**Comment by wss-git** [comment]
Cannot find module './common/client/initOptions'
 
看报错信息是找不到代码的模块，并不是依赖模块， 看起来是和镜像的版本没有关系。

如果可以的话加一下钉钉好友（wssgryx）

**Comment by newbaluku** [comment]
> export FC_DOCKER_VERSION=1.9.21
> 
> Temporarily deal with this first

I switched back to 1.9.21 but the image used is from aliyunfc/runtime-custom:build-1.9.21 and it's not from registry.hub.docker.com/aliyunfc/runtime-custom:build-1.9.21 which is working previously.

Although same version, this image (aliyunfc/runtime-custom:build-1.9.21) also exhibit the same missing module error.
![image](https://user-images.githubusercontent.com/13480257/150093635-6fc321fa-cf95-4ac1-828e-c5c0f6a07b99.png)

seems to be different image, image ID and size is different.

**Comment by newbaluku** [comment]
There seems to be some missing dependencies in the image that the NPM module @alicloud/fc2 needs.

once I removed references to @alicloud/fc2 in my code, my FC run.

**Comment by newbaluku** [comment]
any idea who decides which docker image to use when building custom runtime FC using Serverless-Devs tool?

because it kind of sucks when someone just decided to change the image and my deployment failed for no reason.

**Comment by anycodes** [comment]
Do you have DingTalk or Wechat? I think we could add friends to quickly solve problems.

My wechat： zhihuiyushuaiqi
My dingtalk：17302010206

**Comment by newbaluku** [comment]
> Do you have DingTalk or Wechat? I think we could add friends to quickly solve problems.
> 
> My wechat： zhihuiyushuaiqi My dingtalk：17302010206

Added you via wechat. Somehow, can't find you in dingtalk using the given id

**Comment by newbaluku** [comment]
problem seems to be related to running npm scripts in bootstrap.

details here @ https://github.com/devsapp/start-fc/issues/13
