### ISSUE TITLE
Mac 图标异常

### ISSUE THREAD

**Issue by GreatAuk** [Serverless-Devs/Serverless-Devs#405]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20253809/150448825-18981eae-2725-4fd6-b553-8c439597633d.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 12.0.1 

**Additional context**

**Comment by heimanba** [comment]
desktop暂时没有投入，后面重点投入Vscode插件
