### ISSUE TITLE
添加 layers 属性会导致函数部署失败.

### ISSUE THREAD

**Issue by SoundShell** [Serverless-Devs/Serverless-Devs#414]
function:
        name: http-trigger-nodejs12
        description: "hello world by serverless devs"
        runtime: nodejs12
        codeUri: ./code
        # ossBucket:
        # ossKey:  # conflict with codeUri
        layers: 89caab144b310541b90ef31ce28f9471#test#4
        handler: index.handler
        memorySize: 128
        timeout: 60

✔ Checking Service, Function, Triggers (0.92s)
✖ Creating Service, Function (0.06s)
✖ Creating Service, Function (0.04s)
✖ Creating Service, Function (0.04s)
✖ Project helloworld failed to execute:

ERROR:
PUT /services/hello-world-service/functions/http-trigger-nodejs12 failed with 400. requestid: 9f746672-8fb8-474b-8819-9ccf3fab0583, message: Bad data in request body.

**Comment by anycodes** [comment]
请参考Yaml规范：https://github.com/devsapp/fc/blob/main/docs/zh/yaml.md


![image](https://user-images.githubusercontent.com/21079031/154797249-caade22c-5f16-41aa-9fc8-cd09541e5bf5.png)

在这个规范中，layer的参数是：
```
layer: 
  - xxx
  - xxx
```

关于后期的优化：我们马上就会出verify能力和edit能力，之后可以不用猜是什么参数，也不用翻文档，而是可以通过相关命令校验yaml格式，以及可视化编辑。

- verify：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/command/verify.md
- edit：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/command/edit.md

预计下周可以上线这两个功能
