### ISSUE TITLE
可以支持midway模板吗？

### ISSUE THREAD

**Issue by pilaoda** [Serverless-Devs/Serverless-Devs#450]
两个产品我目前都挺喜欢的。应该都是一家人吧？这么好的机会不联动一下

**Comment by heimanba** [comment]
现在midway已经支持了devs的部署，应用模板方面确实有些缺失，我这两天来加下哈。您能给一些联动的思路或者诉求吗？



---原始邮件---
发件人: "Gengxin ***@***.***&gt;
发送时间: 2022年3月31日(周四) 凌晨0:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Serverless-Devs/Serverless-Devs] 可以支持midway模板吗？ (Issue #450)




 
两个产品我目前都挺喜欢的。应该都是一家人吧？这么好的机会不联动一下

**Comment by pilaoda** [comment]
我也是初学者，谈不上什么思路，只是希望有个配置好的模板可以学习一下。例如可以在s命令里创建已有的模板，在阿里云的Serverless应用里可以直接创建

**Comment by pilaoda** [comment]
也希望说开发时能支持断点调试ts，正式发布时用的是js而不是ts-node（多一步编译），这个我也还在学习中

**Comment by pilaoda** [comment]
我用midway创建的模板是f.yml，如何运行在package.json里也都定义好了，但是我不知道怎么断点调试。
serverless-devs创建的，我就懂得怎么调试，但是他创建的是s.yaml，在midway项目里执行 s 识别不出来。

我目前的诉求其实就是调试midway啦，还在研究中

**Comment by heimanba** [comment]
已经支持 midway koa的应用，通过指令 ` s init start-midway-koa`获取哈

**Comment by pilaoda** [comment]
请问可以不用custom runtime吗？发现custom没法断点调试
