### ISSUE TITLE
端云联调本地断点流程无法走通

### ISSUE THREAD

**Issue by jaylinwang** [Serverless-Devs/Serverless-Devs#459]
**Describe the bug**
使用 serverless devs 进行端云联调，配置vscode 断点始终启动不起来，在启动阶段被异常终止。

**Screenshots**
![image](https://user-images.githubusercontent.com/4530355/161362307-29da69b8-5263-4af8-8c69-c82ae21b06b0.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version: 12.2.1

**Additional context**
使用了serverless devs 初始化模板：start-fc-http-nodejs14

**Comment by rsonghuster** [comment]
端云联调已经支持了nodejs14， 代码昨天才能合并， 预计清明节后会正式发布， dev 版本可以试用
```bash
rm -rf ~/.s/components/devsapp.cn/devsapp/fc-local-invoke@dev
rm -rf ~/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@dev
export core_load_serverless_devs_component='devsapp/fc-proxied-invoke@dev;devsapp/fc-local-invoke@dev'
 ```

可以先执行三个命令， 使用本地调试和端云联调的 dev 版本， 这个是支持 nodejs14 的

**Comment by jaylinwang** [comment]
> 端云联调已经支持了nodejs14， 代码昨天才能合并， 预计清明节后会正式发布， dev 版本可以试用
> 
> ```shell
> rm -rf ~/.s/components/devsapp.cn/devsapp/fc-local-invoke@dev
> rm -rf ~/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@dev
> export core_load_serverless_devs_component='devsapp/fc-proxied-invoke@dev;devsapp/fc-local-invoke@dev'
> ```
> 
> 可以先执行三个命令， 使用本地调试和端云联调的 dev 版本， 这个是支持 nodejs14 的

custom runtime 有计划支持吗

**Comment by rsonghuster** [comment]
> > 端云联调已经支持了nodejs14， 代码昨天才能合并， 预计清明节后会正式发布， dev 版本可以试用
> > ```shell
> > rm -rf ~/.s/components/devsapp.cn/devsapp/fc-local-invoke@dev
> > rm -rf ~/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@dev
> > export core_load_serverless_devs_component='devsapp/fc-proxied-invoke@dev;devsapp/fc-local-invoke@dev'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以先执行三个命令， 使用本地调试和端云联调的 dev 版本， 这个是支持 nodejs14 的
> 
> custom runtime 有计划支持吗

custom runtime 目前调试是支持的， 就是断点调试还没有支持。 有计划： https://github.com/devsapp/fc/issues/697
您也可以说说您的想法， 谢谢！

**Comment by heimanba** [comment]
问题已经解决，欢迎在 https://github.com/devsapp/fc3 提问
