### ISSUE TITLE
OSS 文件解压应用

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#477]
> 该应用可以将用户上传到OSS的压缩包进行解压

入参：
  -  原始OSS Bucket
  -  解压前缀
  -  目标OSS Bucket
  -  目标路径

用户填写原始的Bucket名称和目标Bucket名称，填写原始前缀和目标路径，即可进行应用部署。部署完成，用户只需向原始Bucket上传指定前缀的压缩文件，即可实现自动解压。

- 支持：阿里云函数计算
- 开发上线参考：https://github.com/Serverless-Devs/Serverless-Devs/discussions/439

**Comment by rsonghuster** [comment]
https://github.com/awesome-fc/decompress-oss  

这个目前其实已经有了， OSS 控制台也默认已经集成了 https://github.com/awesome-fc/decompress-oss   其中的 unzip,  内存是3G， 最大执行时长是 1h
