### ISSUE TITLE
报错信息需要更加精确

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#488]
**Describe the bug**
需要区分出来是组件的bug还是，用户在yaml中没有配置component

**Screenshots**
![image](https://user-images.githubusercontent.com/21079031/165227720-762aedc8-1e61-442e-a470-842cae1e2cf6.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by heimanba** [comment]
V2.1.1已经发布
