### ISSUE TITLE
s clean --all 建议清除指定目录

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#490]
node 环境安装在 .s,  s clean --all 直接将环境给干掉了

**Comment by rsonghuster** [comment]
这个命令是清楚 $HOME/.s 所有的东西吗？ 那这个是有问题的

curl 命令行安装， 是把 node 安装$HOME/.s/bin 下面

**Comment by xsahxl** [comment]
> 这个命令是清楚 $HOME/.s 所有的东西吗？ 那这个是有问题的
> 
> curl 命令行安装， 是把 node 安装$HOME/.s/bin 下面

目前是 $HOME/.s 下指定某些文件不删除，其他文件会删除，
后续会改成 只删除某些指定文件

**Comment by heimanba** [comment]
V2.1.1已经发布
