### ISSUE TITLE
Serverless PHP 建站面板

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#495]
## 三篇导读文章：

[PHP 遇见 Serverless](https://docs.serverless-devs.com/blog/php/PHP%E9%81%87%E8%A7%81Serverless)

[Sereverless 网盘](https://docs.serverless-devs.com/blog/php/Serverless_Nas)

[宝塔面板 VS Serverless](https://docs.serverless-devs.com/blog/php/%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF-VS-Serverless)

## PHP 建站面板
PHP 存量应用的迁移以及对宝塔面板使用体感， 我想做一个如下的应用， 这个应用的名字比如叫 "Serverless PHP 建站面板", 会有如下 3 个辅助函数, 在同一个 service 下面：

### 1. kodbox 辅助函数， 管理网站工程上传、下载， 在线编辑 web 工程等等
> [start-fc-kodbox](https://github.com/devsapp/start-fc-kodbox/tree/main/src)， 当然您可以采用其他方案， 但是 kodbox 已经解决的很好了， 尤其是上传文件分片上传解决了FC 6M payload 的限制
![](https://img.alicdn.com/imgextra/i2/O1CN01s88Gcm1F3tr2lQdKe_!!6000000000432-2-tps-1040-337.png)

### 2. 一个有交互页面的函数， 便于用户管理 web，可以参考宝塔面板  
>  任何语言开发都行，前端用户体验需要比较好， 可以先体验下宝塔面板新建一个站点的体验
![image.png](https://img.alicdn.com/imgextra/i2/O1CN01pyyTrO2A0d7t1KJQj_!!6000000008141-2-tps-1500-662.png)

添加一个 web， 就是添加一个 PHP 工程， 即在 NAS 上创建一个目录（比如和宝塔面板一样， 直接以域名创建目录，目录里面有初始化的 index.html 或者 index.php 文件就行 +  和新建一个函数。
后续用户只要使用 kodbox 辅助函数在那个目录上操作对应的文件即可
即新建一个网站 ==  新建一个函数 +  NAS 新建一个目录

### 3 . 数据库这块， RDS mysql 这种直接使用 云厂商 DBMS 管理即可 (可选)
sqlite 数据库有必要也可以提供 web 管理界面，也会新增加辅助函数，[https://github.com/coleifer/sqlite-web](https://github.com/coleifer/sqlite-web)
> ps： 想多个 db 使用一个辅助函数， 但是目前 FC 能力来看， 暂时只能一个数据库一个辅助函数做 web gui 管理
![image.png](https://img.alicdn.com/imgextra/i4/O1CN01Z3iGoU24ckOZMxp7Q_!!6000000007412-2-tps-1500-816.png)
![image.png](https://img.alicdn.com/imgextra/i3/O1CN01Jwq7Zc1wbof38yAte_!!6000000006327-2-tps-1332-706.png)

### 4. SSL 证书体验， 可以参考宝塔面板
![image.png](https://img.alicdn.com/imgextra/i4/O1CN01aPHmg11hfHQFNpWa4_!!6000000004304-2-tps-713-451.png)
或者可以引导用户跳转到 FC 的自定义域名的控制台
![](https://img.alicdn.com/imgextra/i4/O1CN01z2ipnW1RgAKdSOQyI_!!6000000002140-2-tps-1170-621.png)

**Comment by heimanba** [comment]
https://github.com/devsapp/Serverless-Baota 已经实现
