### ISSUE TITLE
希望 Serverless Devs 可以仔细的梳理工具层面的边界条件

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#497]
- [ ] 针对版本进行检测，如果node版本过低，在进行使用的时候，告诉用户版本过低无法执行，需要升级版本，并明确我们所需要的最低版本是多少；
- [ ] 希望在大部分逻辑上，都增加一个try-catch，进行有好的提示，例如没写component的时候，现在的错误是：
```
Please check the value of source in loadComponent function.
```

但是其实用户并不关注啥叫 loadComponent ，我们可以直接更明白告诉用户，没有找到Component，让用户检查一下，yaml配置，是否写了Component

再例如，我yaml中没写service，我直接就是一段：

```
edition: 1.0.0
name: Web IDE
# access 是当前应用所需要的密钥信息配置：
# 密钥配置可以参考：https://www.serverless-devs.com/serverless-devs/command/config
# 密钥使用顺序可以参考：https://www.serverless-devs.com/serverless-devs/tool#密钥使用顺序与规范
access: default

vars: # 全局变量
  region: cn-hangzhou
  name: webide-server
  fcServiceName: ${vars.name}
  fcFunctionName: ${vars.name}
```

我在进行部署的时候，提示我`Cannot convert undefined or null to object`，这种错误就很不友好，所以这里的错误优化，尤其是工具本身的错误优化，是要进行了。

**Comment by heimanba** [comment]
第一个问题我们支持的Nodejs版本已经比较成熟了，可以认为支持到Nodejs8以上的版本。应该是新的版本支持不太好。比如Nodejs17

**Comment by anycodes** [comment]
> 错误提示之前想要依赖AI提示，所以进行的不多。现在确实需要梳理了

但是大家没人补充ai答案。所以ai也发挥不起来作用

**Comment by heimanba** [comment]
3.0 极大优化了错误的报错 体验
