### ISSUE TITLE
s edit 貌似会自动添加一些配置

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#498]
![image](https://user-images.githubusercontent.com/21079031/167757849-2efa79fc-0229-4cc8-a6da-1fb03084bfa6.png)

这里面的PreFreeze和PreStop，貌似是被自己添加进来的，我s init一个项目`start-fc-http-nodejs14 `之后，我进行s verify没问题，我再s edit，直接保存，然后再s verify，貌似就不通过了。这个要查看一下

**Comment by heimanba** [comment]
V2.1.1已经发布
