### ISSUE TITLE
建议新增如何在 CI 环境下发布插件到 registry 的教程

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#503]
目前 Discussions 中对于发布组件到 registry 的教程都是基于 GUI 交互式的, 缺少在 CI 环境中使用命令行进行发布的教程.
例如:

+ [如何快速开发Serverless Devs Package](https://github.com/Serverless-Devs/Serverless-Devs/discussions/407)
+ [快速完成 Serverless Devs 应用开发并发布到 Regsitry](https://github.com/Serverless-Devs/Serverless-Devs/discussions/439)

参考 https://github.com/devsapp/website-fc/blob/master/.github/workflows/registry-publish.yml 时发现有使用一段自定义的 py 脚本以及一个环境变量 `publish_token` 但这个 token 的来源暂时没有找到公开的文档, 后来咨询 @heimanba 时从 .s 文件夹下的一个文件中获取到了这个 token 的值.

**Comment by anycodes** [comment]
这个我可以来支持一下。

**Comment by DevDengChao** [comment]
https://github.com/Serverless-Devs/registry-cli#%E8%8E%B7%E5%8F%96%E7%99%BB%E9%99%86-token
