### ISSUE TITLE
publish yaml 新增一个 x-departed 字段

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#506]
publish yaml 新增一个 x-departed 字段，用来表示这个字段已经废弃了，但是还未移除的一个状态

![image](https://user-images.githubusercontent.com/56686088/168969884-db0fee88-a02c-4a7e-af90-b0fc1ca45f7a.png)

**Comment by DevDengChao** [comment]
或许字段名用 `deprecated` 代替 `x-departed` 更好一些?

参考:
+ https://jsdoc.app/tags-deprecated.html
+ https://nodejs.org/api/deprecations.html
+ https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html
+ https://github.com/json-schema-org/json-schema-spec/issues/74
+ https://github.com/json-schema-org/json-schema-spec/pull/737

**Comment by heimanba** [comment]
是这么考虑的，x-开头代表是自定义schema，不是标准的哈，而且x-开头一般和ui相关。这样在ui层面就不会显示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月15日(周三) 上午9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Serverless-Devs/Serverless-Devs] publish yaml 新增一个 x-departed 字段 (Issue #506)




 
或许字段名用 deprecated 代替 x-departed 更好一些?
 
参考:
  
https://jsdoc.app/tags-deprecated.html 

https://nodejs.org/api/deprecations.html 

https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html 

json-schema-org/json-schema-spec#74 

json-schema-org/json-schema-spec#737

**Comment by xsahxl** [comment]
字段会采用deprecated， 感谢@[DevDengChao](https://github.com/DevDengChao)

**Comment by xsahxl** [comment]
https://github.com/Serverless-Devs/serverless-devs-ui/commit/60fb499951cfe5348fc96ba32e77c15c9e4de78d

https://github.com/Serverless-Devs/serverless-devs-ui/commit/78f50f88b4787ddb73b87744628bf26e6edb7c6a

**Comment by heimanba** [comment]
更新到2.1.2  版本已经支持
