### ISSUE TITLE
Serverless Devs K8s Controller 开发

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#511]
# 背景
Serverless Devs是 Serverless 应用全生命周期管理的工具，可以在本地以及 CI/CD 服务中使用，但目前缺乏对容器生态的支持。我们希望通过该项目提供一个面向 K8s 的控制面组件，实现 Serverless Devs 和其他云原生项目的可集成能力，让容器生态的用户更容易享受 Serverless 服务。选择该项目的同学，需要了解 Serverless 架构并有一定 K8s 项目的开发经验，在项目开发中会比较多的使用 Serverless Devs。

# 技术要求
1. 对Serverless有一定的了解，或者愿意学习和了解Serverless架构
2. 对K8S等有所了解
3. 了解并熟悉对Github等使用方法

# 目标
完成Serverless Devs K8s Controller 的开发

# 难度
进阶

# 导师

[lowkeyrd](https://github.com/lowkeyrd): renda.wrd@alibaba-inc.com

> 【Serverless Devs 介绍】：Serverless是近年来云计算领域热门话题，其凭借着极致弹性、按量付费、降本提效等众多优势获得到了很多人的追捧，各云厂商也在不断的布局Serverless领域。但是随着时间的发展，Serverless领域也暴露出来了一些比较严重的，例如厂商锁定严重，没有合适的开发者工具，程序难以调试......为此，Serverless Devs应运而生，以解决开发者在开发Serverless应用中最根本的诉求为己任，以开源开放的形式为态度，以推动Serverless领域不断前行为目标，Serverless Devs由阿里巴巴诞生，不拘泥于阿里云，放眼云计算，愿开放怀抱与更多Serverlessor一起，玩转Serverless架构。Serverless Devs是一个由阿里巴巴发起的Serverless领域的开源项目，其目的是要和开发者们一起贡献一款开源开放无厂商锁定的Serverless开发者工具，希望这个工具可以在开发者开发Serverless应用的全生命周期发挥作用，希望开发者们可以像使用手机一样玩转Serverless。

**Comment by shubham-cmyk** [comment]
@lowkeryd I am interested in this project . is there any applicant on it ?
