### ISSUE TITLE
Serverless Devs VSCodes插件开发

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#513]
# 背景
作为Serverless应用全生命周期管理工具，Serverless Devs目前还是以命令行的形式存在，故在开发态的支持比较弱。选择该题目的同学，需要了解Serverless Devs相关内容以及具备基本的业务开发能力，完成Serverless Devs的VSCode插件设计与开发。

# 产出要求
1. 设计Serverless Devs的VSCodes插件实现方案，以及实现功能探索
2. 针对设计方案与目标功能，开发插件，并贡献到社区

# 技术要求
1. 对Serverless有一定的了解，或者愿意学习和了解Serverless架构
2. 对Node.js，Typescript等语言有所了解，或者具有较强能力可以快速学习Typescript语言
4. 了解并熟悉对Github等使用方法

# 技术要求
1. 对Serverless有一定的了解，或者愿意学习和了解Serverless架构
2. 对 VScode插件开发有一定的了解
3. 了解并熟悉对Github等使用方法

# 难度
基础

# 导师

@heimanba : yuankun.yk@alibaba-inc.com

> 【Serverless Devs 介绍】：Serverless是近年来云计算领域热门话题，其凭借着极致弹性、按量付费、降本提效等众多优势获得到了很多人的追捧，各云厂商也在不断的布局Serverless领域。但是随着时间的发展，Serverless领域也暴露出来了一些比较严重的，例如厂商锁定严重，没有合适的开发者工具，程序难以调试......为此，Serverless Devs应运而生，以解决开发者在开发Serverless应用中最根本的诉求为己任，以开源开放的形式为态度，以推动Serverless领域不断前行为目标，Serverless Devs由阿里巴巴诞生，不拘泥于阿里云，放眼云计算，愿开放怀抱与更多Serverlessor一起，玩转Serverless架构。Serverless Devs是一个由阿里巴巴发起的Serverless领域的开源项目，其目的是要和开发者们一起贡献一款开源开放无厂商锁定的Serverless开发者工具，希望这个工具可以在开发者开发Serverless应用的全生命周期发挥作用，希望开发者们可以像使用手机一样玩转Serverless。

**Comment by situ2001** [comment]
这里的技术要求duplicate了，请问是前者还是后者呢？

**Comment by anycodes** [comment]
> 这里的技术要求duplicate了，请问是前者还是后者呢？

update

**Comment by ricky11** [comment]
Where and how to obtain the vscode extension to manage fc?
