### ISSUE TITLE
2022 Alibaba Summer of Code

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#514]
# 2022 Alibaba Summer of Code
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻
Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

# What you can get?
On this exclusive developer journey, students will have the opportunity to:
-  Participate in the top projects of the International Open Source Foundation;
-  Get a scholarship from Alibaba;
-  Obtain an open source contributor certificate;
-  Get a fast pass of Alibaba Internship
-  Get your code adopted and used by the open source project！

# Our Mentor
@heimanba :[yuankun.yk@alibaba-inc.com](mailto:yuankun.yk@alibaba-inc.com)
[lowkeyrd](https://github.com/lowkeyrd): [renda.wrd@alibaba-inc.com](mailto:renda.wrd@alibaba-inc.com)

# Timeline
![image](https://user-images.githubusercontent.com/21079031/170020722-5c95a98f-1d45-4539-aad2-ca91e9d0d6ab.png)

# Apply Now!
1. Browse open idea list here:
 - https://github.com/Serverless-Devs/Serverless-Devs/issues/513
 - https://github.com/Serverless-Devs/Serverless-Devs/issues/512
 - https://github.com/Serverless-Devs/Serverless-Devs/issues/511
2. Upload your CV and project proposal via ASOC 2022 official website：
https://opensource.alibaba.com/asoc2022

# Contact the Organizer
If you have any questions, visit the event website:https://opensource.alibaba.com/asoc2022

Email address: opensource@alibaba-inc.com

***Serverless Devs ASOC 2020 DingDing Group：41962007***

**Comment by songhn233** [comment]
Hello, the description of the ASOC2022 idealist looks similar to the projects listed in Open Source Promotion Plan.

The ideas about application development and even their associated GitHub projects are the same. Projects about the vscode extensions also look similar, but the assigned mentor is not the same.

May I ask you to explain the intention of this action, it looks pretty strange. Thanks!

**Comment by anycodes** [comment]
> Hello, the description of the ASOC2022 idealist looks similar to the projects listed in Open Source Promotion Plan.
> 
> The ideas about application development and even their associated GitHub projects are the same. Projects about the vscode extensions also look similar, but the assigned mentor is not the same.
> 
> May I ask you to explain the intention of this action, it looks pretty strange. Thanks!

由于一些工作需求，中科院开源之夏的项目导师临时更换（但是系统没办法处理了），vscode插件的工作都有 @heimanba 负责，对于学生而言，正常申请即可，正常投递简历，给导师发邮件就可以，导师内部会自己来处理。如果有问题可以加钉钉好友：17302010206
