### ISSUE TITLE
Exec Command Removed But Local Invoke Guide To Use it

### ISSUE THREAD

**Issue by lostncg** [Serverless-Devs/Serverless-Devs#515]
**Describe the bug**
When debug an event function locally with command `s local invoke -m server`,
It will create a container for this function to track its operation.
The terminal display a removed command for developer to monitor the logs.

Hence, what is the alternative command to monitor the local event function logs?

**Screenshots**
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/11206864/170169617-1248deed-22a1-4ea2-bfc9-3956fe0f3adc.png">
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/11206864/170169673-bdc9b577-6475-4476-b237-6222e9debfae.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 12.3.1

**Comment by wss-git** [comment]
这个提示错误了，下个版本修复：你可以执行 s local invoke

**Comment by lostncg** [comment]
> 这个提示错误了，下个版本修复：你可以执行 s local invoke

我已经执行了 `s local invoke`，现在希望执行的是 `server` 模式，单开一个容器用以验证定时任务。
单个事件的调用是没有问题的。

**Comment by wss-git** [comment]
验证定时任务目前貌似不支持。local invoke 提示已经修复了
