### ISSUE TITLE
Serverless jupyter

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#521]
目前函数计算支持 http 和 websocket 协议， 同时也支持了 GPU 能力，可以在函数计算应用中心上线一个 

jupyter  + websocket + gpu(AI)

的应用

**Comment by xinwuyun** [comment]
自己部署试了试，体验还不错启动速度也挺快的。但是当实例增多时就会有奇妙的事情发生😂，访问相同链接可能跳到不同实例，导致文件不一致等等相关问题。

果然这种有状态的应用想迁移到 serverless 框架还是要进行一定改造的才能比较完美。

之后有时间可以试试找找解决方案，搞成一个类似 colab 的应用也许是个不错的解决方法。
