### ISSUE TITLE
无法在子目录中校验根目录下有继承关系的 s.yaml 文件的合规性

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#526]
![image](https://user-images.githubusercontent.com/16363180/173001985-e32384c7-9d6c-4ba6-aaa5-1931867ba412.png)

### 问题描述

当在 `s-prod.yaml` 中填写 `extend` 字段时， 如果以 `s-prod.yaml` 自身为相对路径的起点进行填写， 则只能在与 `s-prod.yaml` 同级的目录中对其进行校验。
当在子目录中对上级目录中的 `s-prod.yaml` 进行校验时，`extends` 必须填写以子目录为相对路径起点的路径。

### 用户场景

```
/
- module-1/
- module-2/
     - src/
     - package.json 当用户尝试在这个 package.json 中的 scripts 里引用 ../s-prod.yaml 时会出现上述问题。
- package.json
- s.yaml
- s-prod.yaml
```

**Comment by xsahxl** [comment]
指定yaml文件操作需要 -t 参数指定

**Comment by xsahxl** [comment]
指定yaml文件操作需要 -t 参数指定

**Comment by DevDengChao** [comment]
Ps: `s verify` 没有使用 `-t` 参数指明要校验的 yaml 文档也能正常使用， 不确定是 Bug 还是 Feature 😂。

**Comment by heimanba** [comment]
> 

默认会使用 s.yaml ，所以无需指定`-t`

**Comment by DevDengChao** [comment]
Fixed in https://github.com/Serverless-Devs/core/pull/78
