### ISSUE TITLE
s init 不支持带中文字符的s.yaml

### ISSUE THREAD

**Issue by nideyidayida** [Serverless-Devs/Serverless-Devs#530]
**Describe the bug**
如图，因为有中文字符串所以s init会失败。将”杭州“改为英文即可s init成功。

**Screenshots**
![image](https://user-images.githubusercontent.com/25423569/173488237-8f2a9caa-112f-44e9-92b9-cf713cfd0582.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version @serverless-devs/s: 2.1.0, core: 0.1.38, s-home: /Users/xiuzong/.s, darwin-x64, node-v14.17.3

**Additional context**

**Comment by heimanba** [comment]
更新到2.1.2  版本已经修复
