### ISSUE TITLE
s init 对于定时触发器 payload （jsonstring）里的魔法变量 替换不正确。

### ISSUE THREAD

**Issue by xsahxl** [Serverless-Devs/Serverless-Devs#533]
![image](https://user-images.githubusercontent.com/21330840/173782515-bdfa7bc0-b7bf-4385-99a1-58ff634fe318.png)
![image](https://user-images.githubusercontent.com/21330840/173782569-f8ec8cca-31e6-4b81-9510-8eda0daf9f46.png)

**Comment by heimanba** [comment]
LGTM
