### ISSUE TITLE
FCCI 基于 fc 实现 CI 的功能

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#545]
纯粹使用 FC 做 ci 也不是不可以， 虽然有些能力被阉割， 比如 docker in docker,  但是 95% 以上的需求应该是能被满足的， https://github.com/lambci/lambci  这个 star 就很高。

比如现在 fc 控制台应用中心后端部署就是使用 custom container 函数， 在这个函数里面实现 s.yaml 中 action 中定义的build， 比如 pip install,  npm install以及 mvn package 等等；  设置镜像的编译也可以使用 kaniko 完成 https://github.com/devsapp/start-fc-kaniko

**Comment by anycodes** [comment]
https://github.com/serverless-cd
