### ISSUE TITLE
总是卡在Packing这一步

### ISSUE THREAD

**Issue by Nomango** [Serverless-Devs/Serverless-Devs#553]
**Describe the bug**
`s deploy` 执行后过段时间显示 `Packing` 然后卡住，输出类似这样：

```
Reminder nas upload instruction: upload -r ./ /mnt/auto/hexo

Packing ...
ziping ((█████████████████████░░░░░░░░░░)) 18517677/28068853(Bytes) 65% 2.0s
```

试了很多次，每次卡住的进度不一样，但一定会被卡住

**Desktop (please complete the following information):**
 - OS: windows
 - Version: 19043.1706

**Additional context**

```bash
$ s -v
@serverless-devs/s: 2.1.3, core: 0.1.43, s-home: D:\MyConfiguration\USER\.s, win32-x64, node-v16.15.0
```

**Comment by heimanba** [comment]
> 

建议使用 `website-hexo`

`s init website-hexo`

https://github.com/devsapp/start-website/tree/master/hexo
