### ISSUE TITLE
部署到阿里云函数计算时自定义域名默认没有OPTIONS method导致CORS错误

### ISSUE THREAD

**Issue by andantei** [Serverless-Devs/Serverless-Devs#571]
**Describe the bug**
详见：https://github.com/midwayjs/midway/issues/2216#issuecomment-1211044617

serverless-devs部署自定义域名时会自动去掉OPTIONS: https://tinyurl.com/2lzqxr99 ，导致访问函数非GET方法时的OPTIONS请求返回404，从而导致原请求出现CORS错误。

**Screenshots**
https://tinyurl.com/2lzqxr99 

**Desktop (please complete the following information):**

**Additional context**

**Comment by heimanba** [comment]
您需要，在s.yaml中配置加上 options的类型
![image](https://user-images.githubusercontent.com/5129967/190840192-e8330d40-3ddb-4311-8f0f-405581e08078.png)
