### ISSUE TITLE
缺少 lock 文件导致无法准确定位已发布版本使用的依赖版本

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#574]
**Describe the bug**

调试过程中遇到一些问题, 例如 https://github.com/Serverless-Devs/Serverless-Devs/issues/573 , 尝试定位本地 s 使用的 core 版本时发现全局安装的 s 文件夹中没有 lock 文件, 查看 package.json 发现依赖的 core 也是 latest 版本, 导致无法快速的推断出 s 依赖的 core 到底是哪个版本构建出来的产物.

**Screenshots**

![image](https://user-images.githubusercontent.com/16363180/185540697-4b541798-10b6-40ba-98a4-17862f8448f1.png)

**Additional context**

不只是 core 使用了 latest 导致安装 s 时会出现依赖版本滑动的问题, 其他的第三方依赖也有可能出现小版本出 bug 的情况. 例如: 用户之前安装 s 时依赖了某 lib 的旧版本, 出现了问题, 开发团队复现问题时重新安装 s 依赖了这个 lib 的新版本, 导致无法复现问题. (然后理所当然的告知用户重装 s :rofl: )

https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json:
![image](https://user-images.githubusercontent.com/16363180/185541669-acf924a7-6fd0-4a04-a9dc-6d3a3bf482a2.png)

https://classic.yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control:
![image](https://user-images.githubusercontent.com/16363180/185541776-a1e75ec2-dc78-42eb-8995-81edb250d778.png)

**Comment by heimanba** [comment]
lock文件已经加入
