### ISSUE TITLE
这个Serverless-Devs是不是阿里主导的和serverless framework竞争的产品

### ISSUE THREAD

**Issue by hugetiny** [Serverless-Devs/Serverless-Devs#575]
serverless framework已经够通用了而且是开源的，为啥阿里云还搞一个Serverless-Devs

**Comment by anycodes** [comment]
非常有趣的问题，在之前的Issue中也是回答过一次的。也感谢您对Serverless Devs的关注和支持。

其实Serverless Devs和Serverless Framework在一部分人的眼中，确实有一定的竞争点，但是我并不认为这是竞争。

1. 定位不同：Serverless Devs和Serverless Framework无论是在功能/能力上的定位还是在形态上的定位，其实都是不同的，Serverless Devs作为Serverless应用全生命周期管理工具，会在开发态等投入非常多的支持。包括不限于对端云联调、应用构建等相关部分的探索。另外Serverless Devs一直被认为是工具，Serverless Framework则是框架，这一点在CNCF的Landscape中是可以看到的；

2. 目标不同：Serverless Framework是一个非常优秀开源项目，他更多是在针对全球市场（尤其是北美市场）；Serverless Devs的目标用户群则更为纯粹一些，针对国内市场，努力做最贴近中国开发者的开发者工具；因为目标用户的不同，所以在很大层面上，Serverless Devs会针对国内开发者进行更多的适配，当然白菜萝卜各有所爱，并不能让全部国内开发者用的开心，但是我们希望通过我们的努力，让更多的开发者用的开心和舒心就好了；

另外，我们也非常希望通过我们的努力，可以将这样一个开源项目捐赠给一些中立的团队、组织，我们不仅希望让更多的开发者用好Serverless，我们也非常希望可以回馈开源社区，用更多人的努力，让Serverless开源社区和生态更好。


------

值得一提的是，无论是 Serverless Devs 的模型规范还是工具，还是生态，其实我们都是开源开放的，我们希望可以通过这种开源开放让更多人可以参与建设，让Serverless更好用，更易用。
