### ISSUE TITLE
【维护公告】Serverless Registry 维护公告（2022.10.1 - 2022.11.1）

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#587]
Serverless Registry 作为 Serverless Devs 生态中重要的一部分，我们一直在努力完善 Serverless Registry 相关的功能。

我们预期在 2022.10.1 - 2022.11.1 之间进行 Serverless Registry 的维护，届时 Serverless Registry 开发者将无法将 Package 发布到 Registry，维护完成会恢复该功能。

以下功能不受影响：
1. 正常使用 Serverless Devs （包括下载组件，查询组件等）；
2. 通过其他源进行 Package 更新（包括不限于 Github、Gitee等源）；

For 紧急发布：如果您的 Package 存在紧急发布的情况，为了修改相关功能，您可以：
1. 通过delete进行 Pakcage 回滚；
2. 在当前Issue下留言，并at anycodes，进行紧急操作；

**Comment by Y80** [comment]
你好，请问可以用的 serverless component 去哪里可以看到？找了很多地方了一直找不到

**Comment by anycodes** [comment]
> 你好，请问可以用的 serverless component 去哪里可以看到？找了很多地方了一直找不到

https://registry.serverless-devs.com/

**Comment by anycodes** [comment]
在官网可以看到：

![image](https://user-images.githubusercontent.com/21079031/194683160-6c49c1cc-288a-456f-88c4-e00c162c35ea.png)
