### ISSUE TITLE
YAML 继承支持多级继承

### ISSUE THREAD

**Issue by loganhz** [Serverless-Devs/Serverless-Devs#591]
**Is your feature request related to a problem? Please describe.**

目前yaml 继承只能支持一级，希望可以继承多级。

就是 yaml a 继承 yaml b。然后 yaml c 继承 yaml a

然后想让 c 里有 从 a 和 b 继承下来的内容

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heimanba** [comment]
3.0 已经支持 templete 继承方式。
https://docs.serverless-devs.com/serverless-devs/yaml#template
暂时不考虑支持 多级继承
