### ISSUE TITLE
Serverless Devs 代理模式的支持

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#595]
# 配置相关

【高优先】
增加`s set proxy`，交互式/命令式要求用户配置：
- `http_proxy`
- `https_proxy`
- `http_proxy_user`
- `http_proxy_pass`

帮助信息：

```
Set proxy information.

     Example:
        $ s set proxy
        $ s set proxy --http_proxy xxxx:xxx --https_proxy xxxx:xxx --http_proxy_user xxxx --http_proxy_pass xxxx
        
📖  Document: https://github.com/Serverless-Devs/Serverless-Devs/tree/master/docs/zh/command/set.md

Options:
  -h, --help  Display help for command
```

【中优先】使用全局代理：
```
http_proxy
https_proxy
http_proxy_user
http_proxy_pass
```

【默认】：不支持代理

# 实现相关

1. 在 Serverless 初始化时，进行全局配置：https://www.npmjs.com/package/global-tunnel-ng
2. 调用组件的时候，传入代理相关配置
3. 【组件】拉起docker的时候，给docker配置相关env

**Comment by anycodes** [comment]
> http_proxy_user 和http_proxy_pass 不需要

这个还是需要的，因为很多代理是需要用户名和密码的。

**Comment by heimanba** [comment]
> > http_proxy_user 和http_proxy_pass 不需要
> 
> 这个还是需要的，因为很多代理是需要用户名和密码的。

一般都是把用户名和密码一起的哈，其实最终程序拼接也是这样的。比如 npm 的代理config 设置为
```
npm config set proxy http://username:password@server:port
npm confit set https-proxy http://username:password@server:port
```

**Comment by anycodes** [comment]
> > > http_proxy_user 和http_proxy_pass 不需要
> > 
> > 
> > 这个还是需要的，因为很多代理是需要用户名和密码的。
> 
> 一般都是把用户名和密码一起的哈，其实最终程序拼接也是这样的。比如 npm 的代理config 设置为
> 
> ```
> npm config set proxy http://username:password@server:port
> npm confit set https-proxy http://username:password@server:port
> ```

OK，这样也可以，只要有这个能力就好

**Comment by anycodes** [comment]
该功能如果没什么问题了，需要同步更新中文文档，英文文档，以及模型的规范（SDM）

**Comment by meesii** [comment]
希望docker里面再可以不使用aliyun镜像，1000M宽带速度只有几十kb。
境外的我自带梯子速度都比aliyun快
