### ISSUE TITLE
部署到阿里云失败

### ISSUE THREAD

**Issue by yehonghao** [Serverless-Devs/Serverless-Devs#6]
win10 2004版本

部署后，状态栏左上角已经显示部署结束，里面Triggers:为空。阿里云函数界面未找到对应函数。
Start ......
It is detected that your project has the following project/projects < MyFunctionDemo > to be execute
Start executing project MyFunctionDemo
Waiting for service ServerlessToolProject to be deployed...
(node:13072) ExperimentalWarning: The fs.promises API is experimental
service ServerlessToolProject deploy success
Waiting for function serverless_demo_python3 to be deployed...
Packing ... file .s is ignored. Package complete.
Function: ServerlessToolProject@serverless_demo_python3 updating ...
Deploy function serverless_demo_python3 successfully
function serverless_demo_python3 deploy success
Project MyFunctionDemo successfully to execute
MyFunctionDemo:
Service: ServerlessToolProject
Function: serverless_demo_python3
Triggers: []
![1603886979(1)](https://user-images.githubusercontent.com/16252285/97434314-cb635300-1959-11eb-8004-cc42f9c5774c.jpg)

**Comment by anycodes** [comment]
感谢大佬的支持，首先是这样的，出不来看您这里是部署成功的，您这里可以看一下`template.yaml`内容。这里会描述地点，服务和函数的具体名字的。

至于您说的没有触发器，其实这个可能是一个event函数，如果您需要通过http访问，您可以创建一个http函数：

`s init python3-http -p alibaba && cd python3-http && s deploy`

有任何问题可以继续反馈。随时在线，

**Comment by yehonghao** [comment]
我这边就是启动s gui，然后选择了python3这个例子，配置访问证书后，点击部署，执行窗口为上面输出内容。是我哪里流程错了吗？
template.yaml内容为：
MyFunctionDemo:
  Component: fc
  Provider: alibaba
  Properties:
    Region: cn-hangzhou
    Service:
      Name: ServerlessToolProject
      Description: 欢迎使用ServerlessTool
    Function:
      Name: serverless_demo_python3
      Description: 这是一个Python3的测试案例
      CodeUri: ./
      Handler: index.handler
      MemorySize: 128
      Runtime: python3
      Timeout: 5
  Access: 'ali'

**Comment by anycodes** [comment]
好的，您这里操作是没有错的。是这样的，函数计算实际上你可以简单的分成两个部分：
- 函数本身
- 触发器
您这里是部署了一个函数本身，您如果需要通过http访问的话，还需要部署一个触发器，您如果gui的话，您可以选择这样一个来实验：
![image](https://user-images.githubusercontent.com/21079031/97554864-5bfd6a00-1a12-11eb-8079-a3fb00c57623.png)

这个Python3-http实际上是可以自带一个http触发器，会给您默认返回一个url，您可以通过http方法访问。
