### ISSUE TITLE
s local start 启动本地 serverless 容器如何连接本地的mongo 数据库呢, 网络现在是分开的

### ISSUE THREAD

**Issue by phpmaple** [Serverless-Devs/Serverless-Devs#610]

**Comment by heimanba** [comment]
因为local还是本地的网络， 可以连接到 mogo的公网哈，

**Comment by phpmaple** [comment]
> 因为local还是本地的网络， 可以连接到 mogo的公网哈，

我意思是在 local不能访问 local 的 mongo, 因为serverless 的容器访问不了本机的 localhost

**Comment by heimanba** [comment]
可能容器需要使用本地的网络，这个需要在3.0 的fc组件解决哈,，欢迎在 https://github.com/devsapp/fc3 这里提问
