### ISSUE TITLE
codeUri如果是本地文件夹并且需要打包，支持缓存

### ISSUE THREAD

**Issue by tourze** [Serverless-Devs/Serverless-Devs#613]
我现在是一个service会有多个function，然后几个function是共享一份代码的，只是入参不同。

在 s deploy 时发现几个 function 都会重复打包文件并上传，感觉这一步可以加缓存来提速。

**Comment by heimanba** [comment]
支持全局Action，可以支持这个能力
https://github.com/Serverless-Devs/Serverless-Devs/issues/387

**Comment by tourze** [comment]
> 支持全局Action，可以支持这个能力 #387

不太明白怎么支持，我看全局action一般都是在操作本地文件。
即使我pre deploy时自己压缩了代码文件，最终 codeUri 还是会重复上传多次的吧

**Comment by heimanba** [comment]
> 
是的，这个应该是FC组件的能力。意味着全局的Action能力有了之后，FC组件具备感知到全局的已部署的Service的能力。能够判断是否需要上传代码

**Comment by heimanba** [comment]
这个在3.0的fc组件来跟踪: https://github.com/devsapp/fc3
