### ISSUE TITLE
s 命令的输出是纯字符串

### ISSUE THREAD

**Issue by rsonghuster** [Serverless-Devs/Serverless-Devs#620]
需要：
 s info， 然后获取终端输出的yaml 自己来处理，但是目前output 输出里面有带颜色的字符， 这个是需要自己手动去掉

目标：
有参数可以控制 output 是 raw string， 不需要我们手动出来颜色字符

**Comment by heimanba** [comment]
全局参数: -o/--output
1. -o json
![image](https://user-images.githubusercontent.com/5129967/213065280-4ca70f3b-e3da-44f4-b1c2-ef8eab7e07e3.png)
1. -o raw
JSON不格式化输出
3. -o yaml
默认输出不带颜色
4. -o default
默认输出带颜色的YAML格式
