### ISSUE TITLE
不同云服务商提供的 HTTP 触发器和返回方式不一致，能否抹平差异？

### ISSUE THREAD

**Issue by dreamer2q** [Serverless-Devs/Serverless-Devs#635]
如果不能对齐不同云服务商提供的 HTTP 的触发方式和入参，还不如云服务商提供的 cli 工具。

**Comment by anycodes** [comment]
> 如果不能对齐不同云服务商提供的 HTTP 的触发方式和入参，还不如云服务商提供的 cli 工具。

如果有需要可以选择云服务商提供的工具，Serverless Devs 更多是提供一种规范来做无厂商锁定，而不是去抹平差异。

从工程角度而言，差异是不能被抹平的。差异分为两种：
1. 功能不对齐：这种不可能被抹平
2. 功能对其名称不对齐：这种可以抹平

另外需要明确的是，Serverless devs 是开发者工具，不是开发框架，如果需要抹平运行时和事件规则，需要框架的支持，可以参考 Midway FaaS 等。

**Comment by dreamer2q** [comment]
理解了，使用 `Serverless-Devs` 可以一定程度上减少不同厂商之间的学习成本，例如代码部署、触发器配置等。

至于 HTTP 触发器差异的对齐这个不太容易，我的看法是，新增一个“adapter”适配层用于适配不同的云服务商的差异。

由“Serverless-Devs”提供统一的接口层，可以无缝切换不同的云服务商（也能体现无锁的价值）。

**Comment by dreamer2q** [comment]
补充一点：适配层的存在应该不影响开发框架的选择，例如用户可以自由选择使用 `koa`、`express`、`egg.js` 等。不会因为存在适配层，`Serverless-devs` 就变成了开发框架了。
