### ISSUE TITLE
如何关闭 Tips for next step

### ISSUE THREAD

**Issue by AielloChan** [Serverless-Devs/Serverless-Devs#636]
每次部署完函数后都会打出这一些 tips，比较干扰，如何关闭？
<img width="518" alt="image" src="https://user-images.githubusercontent.com/7900765/216251411-2ef502f6-19f2-449c-acd3-fa701852b097.png">

**Comment by heimanba** [comment]
暂时没有提供关闭能力，这类引导的Tips，后续会精简并且优化

**Comment by lvchenyang** [comment]
因为在CI中调用了通过rushx 命令调用了`rush serverless`，打印这个信息的话，相当于输出了warning，CI就会自动失败，可否换一种输出的方式？
