### ISSUE TITLE
为什么在github actions 理，命令行添加 s config add 加了参数还是要选择是哪个厂商？

### ISSUE THREAD

**Issue by nne998** [Serverless-Devs/Serverless-Devs#638]
在github actions 提交时自动部署命令
`s config add -f -a default -kl AccountID,AccessKeyID,AccessKeySecret -il ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}`

最近会提示这个：
```
Run s config add -f -a default -kl AccountID,AccessKeyID,AccessKeySecret -il ***,***,***

4
? Please select a provider: (Use arrow keys)
5
❯ Alibaba Cloud (alibaba) 
6
  AWS (aws) 
7
  Azure (azure) 
8
  Baidu Cloud (baidu) 
9
  Google Cloud (google) 
10
  Huawei Cloud (huawei) 
11
  Tencent Cloud (tencent) 
12
(Move up and down to reveal more choices)
13
Error: Process completed with exit code 130.
```

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/148901/216260708-6a46ab90-3b1d-4ebe-bedb-7490fa389945.png">

上个月不会的，另外在我本地也不会

**Comment by xsahxl** [comment]
新版本的工具 对 -kl， -il 参数解析的有点问题，可以先通过以下方式避免这个问题哈，下个版本会进行修复。
1. s config add -f -a default --keyList AccountID,AccessKeyID,AccessKeySecret --infoList ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}
2.  s config add -f -a default --AccountID ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}} --AccessKeyID ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}} --AccessKeySecret ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}

**Comment by xsahxl** [comment]
新版本的工具 对 -kl， -il 参数解析的有点问题，可以先通过以下方式避免这个问题哈，下个版本会进行修复。
1. s config add -f -a default --keyList AccountID,AccessKeyID,AccessKeySecret --infoList ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}
2.  s config add -f -a default --AccountID ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}} --AccessKeyID ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}} --AccessKeySecret ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}

**Comment by nne998** [comment]
使用这个可以：  s config add -f -a default --keyList AccountID,AccessKeyID,AccessKeySecret --infoList ${{ secrets.ALIBABA_CLOUD_ACCOUNT_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID}},${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET}}
