### ISSUE TITLE
`actions` 下面没有执行逻辑导致报错

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#653]
![image](https://user-images.githubusercontent.com/5129967/220231535-a087ccba-a9a9-4ef0-b3b0-929f4ef73691.png)

![image](https://user-images.githubusercontent.com/5129967/220231574-27e7d1c6-f70b-4b32-b433-0a138aff29a3.png)

**Comment by xsahxl** [comment]
fix: https://github.com/Serverless-Devs/core/pull/100/commits/33d10c4f305dfc5eb53ecd8bf04c3e26bbf2b78d
