### ISSUE TITLE
如何在s.yaml中配置build相关配置？

### ISSUE THREAD

**Issue by M09Ic** [Serverless-Devs/Serverless-Devs#662]
在自动部署的时候， 希望能打包分散在项目多的各种文件。

文档里关于build部分， 没有yaml配置相关。 也没有在文档中找到Artifact是如何工作的。 

执行命令`s build` ,  只在`.s/fc-build/` 目录下找到一个json文件, 并没有相关的Artifact.

**Comment by anycodes** [comment]
不同的组件要看不同组件的文档，例如build的工作原理：

https://docs.serverless-devs.com/fc/command/build#%E6%93%8D%E4%BD%9C%E6%A1%88%E4%BE%8B

https://docs.serverless-devs.com/fc/tips#%E5%87%BD%E6%95%B0%E8%BF%9B%E8%A1%8Cbuild%E6%93%8D%E4%BD%9C%E4%B9%8B%E5%90%8E%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86build%E7%9A%84%E4%BA%A7%E7%89%A9
