### ISSUE TITLE
E2BIG错误

### ISSUE THREAD

**Issue by weimingli** [Serverless-Devs/Serverless-Devs#670]
在使用ServerlessDevs 进行部署阿里云APIGW的时候，当超过50个以上的API被部署，就会报E2BIG的错误。

**Comment by weimingli** [comment]
✖ Message:

ERROR:

spawn E2BIG

TraceId:     00163e1c56251680476883587
Environment: @serverless-devs/s: 2.1.12, core: 0.1.56, s-home: /root/.s, linux-x64, node-v14.21.1
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues
Regsitry:    https://registry.serverless-devs.com

Please copy traceId: 00163e1c56251680476883587 and join Dingding group: 33947367 for consultation.
A complete log of this run can be found in: /root/.s/logs/00163e1c56251680476883587.log

You can run 's clean --all' to clean Serverless devs.
[2023-04-03 07:08:23] [DEBUG] [S-CLI] - process exitCode: E2BIG

**Comment by heimanba** [comment]
copy that

**Comment by xsahxl** [comment]
https://github.com/Serverless-Devs/toolkit/pull/7/commits/b2b43ce743d15309e8ad24b746f2f84c953a3cbb
