### ISSUE TITLE
serverless.help 国内大面积无法访问, ping 超时

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#674]
![image](https://user-images.githubusercontent.com/16363180/232407454-77e5bcef-ef39-4763-a1bd-ad6e52576a70.png)

See https://ping.chinaz.com/serverless.help

**Comment by DevDengChao** [comment]
![image](https://user-images.githubusercontent.com/16363180/232839353-61c1e86e-06a5-4806-af13-19ccdf2136ec.png)

似乎是域名过期了. 🤣

**Comment by heimanba** [comment]
serverless.help 这个域名在哪里透出的哈？

**Comment by DevDengChao** [comment]
`$ s build --help`

![image](https://user-images.githubusercontent.com/16363180/232951091-bb3658b2-f378-4327-89ae-624e6c4b5c59.png)

**Comment by DevDengChao** [comment]
现在访问 https://serverless.help/t/build 能够正确的重定向到 https://docs.serverless-devs.com/fc/command/build 了.
