### ISSUE TITLE
无法理解，如何配置runtime,指定node版本

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [Serverless-Devs/Serverless-Devs#677]
在部署next13的时候，发现系统只用nodejs14进行部署，导致一直报版本过低无法运行。
翻阅所有文档只找到一个runtime，配置了nodejs16，问题依旧。。。我很好奇，大家都不指定node版本吗？
有时候有的项目需要低版本的nodejs，有的需要高版本。java也应该有这种情况吧。。这种环境下如何运行？

**Comment by liuhuapiaoyuan** [comment]
我指的是service/pre-deploy，并不是function

**Comment by heimanba** [comment]
`s init start-next`看下效果，就是 next13的哈

**Comment by cqh963852** [comment]
@liuhuapiaoyuan 可以说一下具体是怎么解决的吗？也碰到相同的问题了。

**Comment by liuhuapiaoyuan** [comment]
> @liuhuapiaoyuan 可以说一下具体是怎么解决的吗？也碰到相同的问题了。

忘记了，sorry，记得好像有一个 label 配置

**Comment by zxypro1** [comment]
@cqh963852 可以 `s init start-next` 看一下 `s.yaml` 文件，用的是custom runtime + customRuntimeConfig + actions的方法
