### ISSUE TITLE
s config add 时提示 TypeError: Yie.default.makeLogFile is not a function

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#680]
**Describe the bug**
如题

**Screenshots**
![image](https://user-images.githubusercontent.com/16363180/235050995-4717ade6-df1c-42b8-ac82-2800c82ce56d.png)

**Additional context**

s: 2.1.13
NodeJS: 18.16.0
运行环境: 云效 NodeJS 步骤
聆听反馈: https://connect.console.aliyun.com/connect/detail/415691

**Comment by heimanba** [comment]
这个是本地 `package-lock.json` 需要更新下，否则会下载到老的`@serverless-devs/core` 包
