### ISSUE TITLE
每次执行s deploy都是执行以前的s.yaml缓存

### ISSUE THREAD

**Issue by dh-free** [Serverless-Devs/Serverless-Devs#684]
我s.yaml改了无数回，每次执行deploy永远执行的是第一次写的配置，我都不知道缓存在哪了，s clean --all都不起作用

**Comment by anycodes** [comment]
是不是你用了remote？要不执行的时候选择use-local？货也可以看看改的yaml和部署使用的是不是一个？

**Comment by dh-free** [comment]
> 是不是你用了remote？要不执行的时候选择use-local？货也可以看看改的yaml和部署使用的是不是一个？

s deploy --user-local 都试过了，也选的本地本件，但就是执行的是我老早之前的yaml配置，我改了服务名，部署出去的还是旧服务名

**Comment by Revolver-T** [comment]
楼主解决这个问题了吗

**Comment by heimanba** [comment]
这个问题还存在吗？

**Comment by heimanba** [comment]
有问题可以加入Serverless开发者学习群交流哈： 33947367
