### ISSUE TITLE
s工具无法拉取github上的组件，与SDM规范不符

### ISSUE THREAD

**Issue by leibnewton** [Serverless-Devs/Serverless-Devs#687]
**Describe the bug**

我们开发了一个serverless-devs组件在github，也创建了release，但是s工具拉取不成功。使用的命令为：

`s cli sihecloud/sae-api list --debug`

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/19380871/f201f237-b89c-467a-bb5b-9ed8cca30702)

**Desktop (please complete the following information):**
 - OS: Darwin (macOS Ventura 13.3.1)
 - Version 22.4.0

**Additional context**

目前得到的回复是必需将组件推送到Serverless Registry，s工具才能拉取。

**Comment by anycodes** [comment]
初步看是拉github的时候403，需要 @heimanba 支持一下

**Comment by heimanba** [comment]
由于GitHub的api更改了，所以失效了
