### ISSUE TITLE
当 yaml 中配置的 package name 和组件的方法重名时，简写会解析异常

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#688]
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/56686088/d4285ac8-405c-4e3c-9038-34ad41952fbd)

**Comment by heimanba** [comment]
> 已在最新beta版修复。现在若名字跟指令重叠，会报错并提示修改名字。

`npm i @serverless-devs/s3@beta -g`
