### ISSUE TITLE
[p0体验问题] CustomContainerConfig 缺少 WebServerMode字段

### ISSUE THREAD

**Issue by nideyidayida** [Serverless-Devs/Serverless-Devs#689]
**Describe the bug**
CustomContainerConfig 缺少 WebServerMode字段 

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/25423569/74e2f922-b984-4ace-8478-082604f9b0ed)

**Desktop (please complete the following information):**

**Additional context**
官方文档 https://help.aliyun.com/document_detail/415677.html

**Comment by lowkeyrd** [comment]
可以直接在s.yaml中使用这个参数，文档我们会补充下。
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/5763215/17d894f9-c903-4465-a3a0-b3f925ef8893)
