### ISSUE TITLE
请问如何在deploy时排除一些文件夹

### ISSUE THREAD

**Issue by JsonSong89** [Serverless-Devs/Serverless-Devs#694]
deploy逻辑看起来是把codeUri整个文件夹打zip包然后上传zip包
请问有没有什么配置可以排除一些文件夹,比如test,template之类部署时不需要的文件夹.

我现在是跑脚本复制出一个想要的文件夹再deploy,如果可以在zip时通过入参控制就更方便了.

**Comment by wss-git** [comment]
可以看看这个块哈：
https://docs.serverless-devs.com/fc/tips#%E5%85%B3%E4%BA%8Efcignore%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by JsonSong89** [comment]
谢谢 看文档时漏掉了
