### ISSUE TITLE
Message: No start-nodejs14-tablestore-http app found. 

### ISSUE THREAD

**Issue by cy666697** [Serverless-Devs/Serverless-Devs#697]
s init start-nodejs14-tablestore-http -d start-nodejs14-tablestore-http

◆ More applications: https://registry.serverless-devs.com

WARNING:
======================
* Please make sure the app name or source is correct, you can get applications on Serverless Regsitry: https://registry.serverless-devs.com

Message: No start-nodejs14-tablestore-http app found.

You can run 's clean --all' to clean Serverless devs.

**Comment by heimanba** [comment]
已经可以找到： https://www.devsapp.cn/search.html?keyword=start-nodejs14-tablestore-http
