### ISSUE TITLE
FC/build（https://docs.serverless-devs.com/fc/command/build）错别字

### ISSUE THREAD

**Issue by LeiFeng1000** [Serverless-Devs/Serverless-Devs#699]
1. "为了能函数”改为“为了能使函数”或者“为了函数”。原文：如上所示，so 底层 lib 全部安装到 .s/root 目录下面， 为了能函数能正确使用到这些 so 文件， 最后 deploy 的时候给函数增加下面两个环境变量即可
2.

**Comment by heimanba** [comment]
fixed: https://github.com/devsapp/fc/blob/main/docs/zh/command/build.md
