### ISSUE TITLE
s deploy Nuxt3 应用导致线上服务端缺少 lru-cache 包

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/Serverless-Devs#701]
**Describe the bug**

1. 使用 Nuxt3 构建任意应用. 并添加包含 lru-cache 的包, 例如 mysql2.
2. 使用 `nuxt build` 命令构建应用到 .output 目录
3. 使用 `s deploy` 命令将 .output 目录部署到 FC
4. 对比本地 `.output/server/node_modules` 与 FC IDE 或实例中的 `.output/server/node_modules`  发现线上缺少 lru-cache 包.

**Screenshots**
本地 .output :
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/16363180/06f1a6aa-a258-4d00-a409-233c9f542735)

线上:
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/16363180/538770ce-e21b-40ba-a2b2-cfde388a2963)

**Additional context**

晚点我再补充一个示例工程.

**Comment by DevDengChao** [comment]
目前可行的变通方案是手动将 .output 压缩成 .output.zip 再部署.

**Comment by heimanba** [comment]
为啥仅会出现 `lru-cache`的包被`ignore`了呢？是不会应该所有的`node_module`包都被`ignore`呢

**Comment by DevDengChao** [comment]
> 为啥仅会出现 `lru-cache`的包被`ignore`了呢？是不会应该所有的`node_module`包都被`ignore`呢

很难说清楚为啥会出现这个现象, 毕竟 s 的测试覆盖率不是很高 :rofl:, 我这边仅可以提供录屏证据.

**Comment by heimanba** [comment]
3.0 加强了整个测试覆盖了哈，欢迎使用fc3.0配套sevrerless-devs3.0 , npm i @serverless-devs/s3 -g
