### ISSUE TITLE
删除AccessKeyID 

### ISSUE THREAD

**Issue by 11111111-T** [Serverless-Devs/Serverless-Devs#703]
Please create alias for key pair. If not, please enter to skip (default):
  AccessKeyID:     *****************
  AccessKeySecret: ******************************
  AccountID:       ****************
  
  s config delete -a  Please create alias for key pair. If not, please enter to skip (default) 不起作用

**Comment by heimanba** [comment]
升级到3.0解决哈， npm i @serverless-devs/s3  -g
