### ISSUE TITLE
podman不支持json指令

### ISSUE THREAD

**Issue by Matiz7** [Serverless-Devs/Serverless-Devs#705]
# /usr/local/node-v21.0.0/bin/s build --use-sandbox
[2023-10-20 13:27:26] [INFO] [FC-BUILD] - Build artifact start...
Error: template parsing error: template: image:1: function "json" not defined
✖ Project cn-shanghai-pms_service-GaodeProxy failed to execute:

ERROR:
Command failed: docker info --format "{{json .}}"
Error: template parsing error: template: image:1: function "json" not defined
TraceId:     e0d55ec6dd4b1697779646383
Environment: @serverless-devs/s: 2.2.0, core: 0.1.64, s-home: /home/admin/.s, linux-x64, node-v21.0.0

# docker info --format "{{json .}}"
Error: template parsing error: template: image:1: function "json" not defined

# podman -v
podman version 1.6.4

Command failed 就不能判断$? 然后换个办法  不过是解析yml文件

**Comment by heimanba** [comment]
这里使用了[dockerode](https://www.npmjs.com/package/dockerode) 这个 包来管理docker ,对于不同的版本有些兼容的问题。建议升级到函数计算3.0， 工具在3.0解决了类似的问题
https://docs.serverless-devs.com/fc3/command/build
