### ISSUE TITLE
s3@0.0.14, s init 指令选择阿里云，custom-domain ，报错

### ISSUE THREAD

**Issue by wangshixiang** [Serverless-Devs/Serverless-Devs#707]
**Describe the bug**
s3@0.0.14, s init 指令选择阿里云，custom-domain ，报错

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/16265387/560536de-2e5f-488c-bb7e-3a478da67323)

**Comment by zxypro1** [comment]
是因为配置文件未更新，已在0.0.15-beta.5版本中修复，可以`npm i @serverless-devs/s3@beta -g`尝试一下
