### ISSUE TITLE
能否考虑支持daemon模式方便二次集成

### ISSUE THREAD

**Issue by DVKunion** [Serverless-Devs/Serverless-Devs#709]
需求：希望s工具能以一种守护进程的方式作为长停留的服务，监听某个端口，通过协议/socks通信将要deploy的函数配置传递给守护进程，执行。

使用场景：我的项目是一个支持多云部署的函数工程，期望写一个配置页面，让用户选择输入云厂商后输入对应配置，直接使用s工具一件部署；而不是在自己对接各厂家sdk。

除此以外，在一些其他持续集成的场景下也可能会有用：比如这样就可以开发一个编辑器插件，当代码保存后自动部署到函数环境，而不需要每次手动执行`s deploy`诸如此类。

**Comment by heimanba** [comment]
理解，由于整体架构的原因，daemon模式改造暂时还没有计划支持哈，我把这个需求记录在feature列表中
