### ISSUE TITLE
S-CLI-ERROR

### ISSUE THREAD

**Issue by zhangucan** [Serverless-Devs/Serverless-Devs#71]
s config delete 操作后，配置文件存坏。如何修复？
![image](https://user-images.githubusercontent.com/26155364/118687144-4416f780-b837-11eb-900e-154fdfc78288.png)
![image](https://user-images.githubusercontent.com/26155364/118687194-52651380-b837-11eb-8592-81008d2e4813.png)

**Comment by zhangucan** [comment]
![image](https://user-images.githubusercontent.com/26155364/118688935-192da300-b839-11eb-9bb5-28c5861c03a7.png)
默认在 ～ 下，把文件格式调整一下就好了

**Comment by zhangucan** [comment]
需要一个默认的default 的公司钥

**Comment by anycodes** [comment]
感谢您的提醒，我们今天针对密钥配置进行一次升级改造，争取不会出现问题
