### ISSUE TITLE
文档滞后

### ISSUE THREAD

**Issue by wss-git** [Serverless-Devs/Serverless-Devs#718]
https://docs.serverless-devs.com/serverless-devs/cicd

![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/56686088/707ff79c-e92e-414c-b6da-e97434330db4)
<img width="620" alt="41fadb6c307481820ac35f397000e22d" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/56686088/3f4a8a54-ac94-4465-96a6-9db2b2c44089">

里面的node版本太低了哈，导致程序流水线挂掉

**Comment by heimanba** [comment]
fixed
