### ISSUE TITLE
升级 s 工具版本偶发报错

### ISSUE THREAD

**Issue by loganhz** [Serverless-Devs/Serverless-Devs#719]
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/21168270/f0af3b04-8994-4494-ab47-59c568eea7fd)

npm install 报错，无法升级 s 工具版本

**Comment by zxypro1** [comment]
应该是之前安装的时候有用权限，可以删除`/usr/local/lib/node_modules/@serverless-devs/s`目录后再试一下。另外尽量不要使用sudo安装。
