### ISSUE TITLE
s deploy 发布失败 报错：spawn pulumi ENOENT

### ISSUE THREAD

**Issue by zhangucan** [Serverless-Devs/Serverless-Devs#72]
![image](https://user-images.githubusercontent.com/26155364/118690115-50508400-b83a-11eb-9fa4-c3a9e1ad1484.png)

**Comment by anycodes** [comment]
@git-qfzhang 麻烦关注一下这里。另外 @wss-git 我们是否可以尽快有sdk的部署方案？

**Comment by git-qfzhang** [comment]
已经修复，麻烦重试一下

**Comment by zhangucan** [comment]
需要安装新版本cli吗？
