### ISSUE TITLE
函数计算3.0项目无法publish到Serverless Registry，Serverless Registry是否还不支持函数3.0？

### ISSUE THREAD

**Issue by Sunny-Law** [Serverless-Devs/Serverless-Devs#743]
使用的Serverless Devs版本：3.0.0
使用命令：s cli registry publish
一开始提示Edition must be 2.0.0 / 1.0.0 version. Please join DingTalk group: 33947367 for consultation
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/26264216/89e05e46-29ab-4fb9-b9b3-d50b496ff29a)
但即使将publish.yaml中的Edition: 3.0.0注销后，仍然提示未知错误
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/26264216/670fa8a7-0dc1-4859-a8ec-1ec316ff8871)

**Comment by heimanba** [comment]
@zxypro1 这个错误信息也不对，是不是应该指引 `s cli registry login`

**Comment by Sunny-Law** [comment]
@heimanba 已经使用s cli registry login登录成功，函数计算2.0的项目publish没有问题，只有函数计算3.0的项目会这样

**Comment by zxypro1** [comment]
s cli registry publish只支持老模版，3.0.0的模版需要使用s registry publish指令。
