### ISSUE TITLE
阿里云FC平台不可以更改容器基础镜像版本

### ISSUE THREAD

**Issue by charlescui** [Serverless-Devs/Serverless-Devs#752]
**Describe the bug**
使用s命令创建一个express的web项目，代码目录如下

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/875374/2729494a-554b-4d99-8f9c-a05754fa9eb8)

项目初始化后，自动第一次部署。
开发写代码，并且调整Dockerfile中的node版本，Dockerfile如下
```bash
FROM node:18-slim

WORKDIR /home/code
COPY . .
```
使用s deploy命令发布服务到线上，发布多次，容器启动全都失败，原因是线上容器的node版本依然是最初的Dockerfile版本10，而不是Dockerfile中指定的18。

![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/875374/bc74d61d-bb89-4ed4-bf82-66ae02bebc85)

为什么阿里云FC不可以更改容器的基础镜像版本？

**Desktop (please complete the following information):**
 - OS: macos
s工具信息:
```bash
@serverless-devs/s: 2.2.0, core: 0.1.66, s-home: /Users/xxx/.s, darwin-arm64, node-v18.16.0
```

**Comment by heimanba** [comment]
@charlescui 这个不是bug,你在webide里面执行node -v 其实是webide的镜像的版本。你的dockerfile里面的版本，可以试着在代码执行下node -v看看。在webide执行的是 wedide容器的镜像的nodejs版本哈
