### ISSUE TITLE
Mac m1 Error: Interaction in cicd environment, throwing exception

### ISSUE THREAD

**Issue by www-YM** [Serverless-Devs/Serverless-Devs#754]
**Describe the bug**
执行 `s config add` 报错

**Screenshots**
<img width="637" alt="s error" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/570c28a0-8ef1-481a-a784-8495d9e2c0da">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.2 (22D49)
 - Chip: Apple M1

**Additional context**
开发者好，我第一次使用 Serverless-Devs。不管是通过 yarn 安装还是 release 下载，在执行的时候都提示这个错误。
这个错误要怎么解决？

**Comment by zxypro1** [comment]
可以试试使用 `npm install @serverless-devs/s -g` 安装吗？

**Comment by www-YM** [comment]
<img width="711" alt="Screenshot 2024-01-21 at 15 48 30" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/10df57ec-8d7f-4dcd-8493-fd5c8dfed14f">
奇怪，我在 ecs 上安装也不行，同样的错误

> 可以试试使用 `npm install @serverless-devs/s -g` 安装吗？

**Comment by zxypro1** [comment]
可以打印一下环境变量吗？

**Comment by www-YM** [comment]
<img width="912" alt="Screenshot 2024-01-21 at 15 57 36" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/81ca9c27-3bbf-4308-aa39-f271805f392e">

这是阿里云 ECS Ubuntu22 上的

> 可以打印一下环境变量吗？

**Comment by www-YM** [comment]
喔，我阿里云上另外创建一个新的 ECS，直接使用 apt 安装的 nodejs18 执行`npm install @serverless-devs/s -g`就不报错了，前面测试的都是用 nvm 安装的 nodejs。
---------
因为我需要 nvm 做 nodejs 的版本管理，需要额外设置什么才能正常使用 Serverless-Devs 吗？

**Comment by zxypro1** [comment]
理论上nvm也是可以正常使用的，看上去很可能是因为 `GITLAB_NPM_AUTH_TOKEN` 这个环境变量让serverless-devs误以为是cicd环境而不是交互环境，可以删除后试一下。

以及，这类token暴露在外会很危险，最好删除或者打个码再发出来。

**Comment by www-YM** [comment]
谢谢！可以正常使用了

> 理论上nvm也是可以正常使用的，看上去很可能是因为 `GITLAB_NPM_AUTH_TOKEN` 这个环境变量让serverless-devs误以为是cicd环境而不是交互环境，可以删除后试一下。
> 
> 以及，这类token暴露在外会很危险，最好删除或者打个码再发出来。
