### ISSUE TITLE
升级相关提示 不对

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#757]
![Image](https://github.com/Serverless-Devs/Serverless-Devs/assets/5129967/9adc4bd3-e3bd-4e0a-9ab9-93af1f7342be)

![Image](https://github.com/Serverless-Devs/Serverless-Devs/assets/5129967/dbe6a535-fa91-462f-9eb2-dc729c536023)

**Comment by huyikun** [comment]
原因是第三方库 latest-version api 出错
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/48144200/85397044-42f4-4ada-9c02-45b3887e1f9d)
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/48144200/6c675551-c488-4b0a-9a25-8ac275cc2532)

**Comment by zxypro1** [comment]
第三方库的问题，目前已不再出现
