### ISSUE TITLE
为什么 s 命令在阿里云的设备上 .s 的目录会不一样

### ISSUE THREAD

**Issue by AielloChan** [Serverless-Devs/Serverless-Devs#763]
**Describe the bug**
普通设备上运行 .s 命令，s home 是在 ~/.s 目录，但是在阿里云的服务器上，s home 是 ~/.cache/.s 这是为什么呢？

能不能统一一下？虽然 s -v 能输出 s home，但是 他输出的是想下面这样的非结构化数据，都不好去解析出实际的 s home 目录，硬字符串匹配，担心下次结构变了，就会失败，结构化的至少表示官方是会维护这个结构的。

```txt
@serverless-devs/s3: 0.1.1, s-home: /Users/xxxx/.s, darwin-arm64, node-v20.10.0
```

## CI/CD 模式

另外有一个需求是我需要在 CI/CD 流程中使用 s 命令，但每次部署函数都会全新下载一批的组件，这个 s 命令能不能提供一个预下载的功能，我把这些组件打包到基础镜像中，提高速度。感谢

下面是 s deploy 运行后，下载组件的输出

```
- Downloading: [/devsapp/fc/zipball/0.1.72]
✔ devsapp_fc.zip file decompression completed
- Downloading: [/devsapp/core/zipball/0.1.66]
✔ core@0.1.66.zip file decompression completed
- Downloading: [/devsapp/fc-core/zipball/0.0.35]
✔ devsapp_fc-core.zip file decompression completed
- Downloading: [/devsapp/fc-deploy/zipball/0.0.120]
✔ devsapp_fc-deploy.zip file decompression completed
- Checking Function app exists
- Downloading: [/devsapp/fc-plan/zipball/0.0.47]
✔ devsapp_fc-plan.zip file decompression completed
- Checking Function app exists
- Downloading: [/devsapp/fc-info/zipball/0.0.41]
✔ devsapp_fc-info.zip file decompression completed
✔ Checking Function (2.5s)
- Creating Function wolai-page-service/app...
✔ Creating Function (1.31s)
- custom container acceleration status...
```

**Comment by zxypro1** [comment]
1. s的会取环境变量$HOME作为.s的位置，是不是服务器的$HOME有问题？另外s -v的输出其实就是结构化输出，官方维护的，格式为`${pkg.name}: ${pkg.version}`, `s-home: ${getRootHome()}`, `${process.platform}-${process.arch}`, `node-${process.version}`
2. 感谢反馈，内部会考虑下这个需求。

**Comment by AielloChan** [comment]
> 1. s的会取环境变量$HOME作为.s的位置，是不是服务器的$HOME有问题？另外s -v的输出其实就是结构化输出，官方维护的，格式为`${pkg.name}: ${pkg.version}`, `s-home: ${getRootHome()}`, `${process.platform}-${process.arch}`, `node-${process.version}`
> 2. 感谢反馈，内部会考虑下这个需求。

我看了 core 的源码，是通过判断 process.env.PIPELINE_ID 和 process.env.CLI_VERSION 这两个环境变量，来确定 s home 的

**Comment by zxypro1** [comment]
3.0版本的cli已经不是用core里面的判断逻辑了，用的是utils包的getRootHome方法，在不存在`serverless_devs_config_home`这个环境变量的时候默认会取`os.homedir()`。

只有在云效中使用的时候，路径会是~/.cache/.s。所以是在云效中使用的吗？

**Comment by AielloChan** [comment]
> 3.0版本的cli已经不是用core里面的判断逻辑了，用的是utils包的getRootHome方法，在不存在`serverless_devs_config_home`这个环境变量的时候默认会取`os.homedir()`。
> 
> 只有在云效中使用的时候，路径会是~/.cache/.s。所以是在云效中使用的吗？

<img width="1215" alt="image" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/7900765/349bbef4-efce-448c-8c9c-1fdc6e8c671b">

我是在 aone 的自定义流水线中使用的，的确是有 PIPELINE_ID 这个环境变量

**Comment by zxypro1** [comment]
那确实是会使用~/.cache/.s作为路径了。可以针对s -v解析下，结构是基本不会变的。
