### ISSUE TITLE
3.0.1 版本 devs-cli 执行 s registry publish 报错

### ISSUE THREAD

**Issue by neurotoxinvx** [Serverless-Devs/Serverless-Devs#777]
**Describe the bug**

```bash
s init start-application-v3
s registry publish

报错

```
[2024-02-22 18:56:49][ERROR][s_cli] Publish.yaml illegal:
yamlPath: ~/start-application-v3/publish.yaml
schemaPath: #/properties/Service/additionalProperties
message: must NOT have additional properties

Error Message:
Publish.yaml illegal.
  Application dev: https://docs.serverless-devs.com/serverless-devs/development-manual/readme
  Component dev: https://docs.serverless-devs.com/serverless-devs/development-manual/component
  Plugin dev: https://docs.serverless-devs.com/serverless-devs/development-manual/plugin
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 3.0.1

**Additional context**
Add any other context about the problem here.

**Comment by zxypro1** [comment]
publish.yaml可以发来看一下吗

**Comment by neurotoxinvx** [comment]
@zxypro1 就是 s init start-application-v3 默认的 publish.yaml

**Comment by neurotoxinvx** [comment]
`Edition: 3.0.0
Type: Project
Name: 名称
Version: 版本，例如0.0.1 或者 dev
Provider:
  - 阿里云 # 取值内容参考：https://api.devsapp.cn/v3/common/args.html
Description: Serverless Devs 应用开发模板
HomePage: https://www.serverless-devs.com
Tags: #标签详情
  - 模板
  - Serverless Devs
Category: 新手入门 # 取值内容参考：https://api.devsapp.cn/v3/common/args.html
Service: # 使用的服务
  服务名: # 取值内容参考：https://api.devsapp.cn/v3/common/args.html
    Authorities: #权限描述
      - AliyunFCFullAccess # 所需要的权限
# Organization: 阿里云函数计算（FC） # 所属组织
Effective: Public # 是否公开，取值：Public，Private，Organization
Parameters:
  type: object
  additionalProperties: false # 不允许增加其他属性
  required: # 必填项
    - region
  properties:
    region:
      title: 地域
      type: string
      default: cn-hangzhou
      description: 创建应用所在的地区
      enum:
        - cn-beijing
        - cn-hangzhou
        - cn-shanghai
`

**Comment by zxypro1** [comment]
里面一些信息是需要手动填写，不改的话无法发布的哈
