### ISSUE TITLE
2.0应用改成3.0 的协议报错信息很难理解

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#778]
## 复线步骤
1. s init start-express
2. 将s.yml edition改成3.0.0
3. 报错信息为：
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/5129967/26d3ba92-98d3-44fb-b961-9965dd655e98)

**Comment by cqh963852** [comment]
碰到了相同的问题，很困惑是否需要添加 Step

**Comment by zxypro1** [comment]
已在最新beta上加上友好提示
