### ISSUE TITLE
The ots table backup application specifies a service role, but the deployed service uses the default role.

### ISSUE THREAD

**Issue by zolaer9527** [Serverless-Devs/Serverless-Devs#795]
**Describe the bug**
When I deployed the "ots-table-backup" application in the Alibaba Cloud Serverless Application Center, the template required to specify a RAM role that has the AliyunOTSFullAccess policy. However, after the application was deployed, there was a service named ots-table-backup. The role used by this service was aliyunfcdefaultrole.

**Screenshots**
Before the application deployed:
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103011488/01e75b34-af52-49ec-a710-e8138c185b0e)
After the application deployed:
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103011488/ad0c0ac3-7b1d-497f-8a24-62ae069da6b4)

**Comment by zxypro1** [comment]
For Alibaba Cloud issues, you can report via [Alibaba Cloud Support Center](https://smartservice.console.aliyun.com/service/list) and get help.

**Comment by zolaer9527** [comment]
Thank you for your suggestion.

**Comment by zolaer9527** [comment]
But this issue may be a bug, [Alibaba Cloud Support Center](https://smartservice.console.aliyun.com/service/list) can't resolve this issue. Besides, I found this report way in [the source code of the application](https://github.com/devsapp/ots-table-backup?tab=readme-ov-file#%E5%BC%80%E5%8F%91%E8%80%85%E7%A4%BE%E5%8C%BA). And it said, "If you have any feedback about errors or future expectations, you can provide feedback and communicate in the [Serverless Devs repo Issues](https://github.com/serverless-devs/serverless-devs/issues)." If this is not the right way, could you tell me where I should report the bug issue about the application?

**Comment by zxypro1** [comment]
Looks like a bug. @lowkeyrd

**Comment by lowkeyrd** [comment]
> Looks like a bug. @lowkeyrd

Yes, it has been fixed. You can try it again.
https://github.com/devsapp/ots-table-backup/commit/d852ee17c399d5f8483630cf17c3bce207da1f79

**Comment by zolaer9527** [comment]
Thank you for your fix. By the way, about the security issue of other applications in the Alibaba Cloud Serverless Application, I wrote an email to [service@serverlessfans.com](mailto:service@serverlessfans.com) a week ago. Have you received the email?

**Comment by zxypro1** [comment]
@anycodes

**Comment by zolaer9527** [comment]
Besides, the fc-qwen application has a similar bug. During the deployment of the fc-qwen, I specified the RAM role, but the service created by the application used no roles, it is n/s. 
Before the deployment:
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103011488/7cdbff82-ea34-4409-a344-5812dc384928)

After the deployment:
![服务角色](https://github.com/Serverless-Devs/Serverless-Devs/assets/103011488/290eead1-0272-4c13-9809-7df6e00b7153)
