### ISSUE TITLE
发布自定义容器时，docker login --password-stdin 疑似在 windows command propmt 中失效

### ISSUE THREAD

**Issue by pilaoda** [Serverless-Devs/Serverless-Devs#805]
试了两台电脑，win10 win11 都一样，必须得在powershell中才行

![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/12658348/48d02660-e2ee-4c29-92a4-793afad0c0a3)

`echo xxx | xxx`，在cmd和powershell中表现不一样

不管调用`s deploy`的是cmd还是powershell，fc3里面，spawn子进程登录都会失败
能不能在 windows 强制用 powershell 来登录 docker ？

**Comment by pilaoda** [comment]
或者能不能用旧版fc的登录方法，之前一直没问题，用了fc3才登录不了

**Comment by pilaoda** [comment]
https://stackoverflow.com/questions/21566707/piping-in-windows-cmd-exe-doesnt-forward-standard-output-until-the-process-comp

**Comment by zxypro1** [comment]
新版工具也是支持旧版yaml的，直接运行就可以。新旧版fc登陆的输出分别是什么样的呢？

**Comment by pilaoda** [comment]
我知道支持旧版，我就是在试用新版。就是相当于没有输入
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/12658348/6ffa18a6-a733-483a-87f8-b5269765a201)

**Comment by zxypro1** [comment]
@rsonghuster 帮忙看下吧

**Comment by pilaoda** [comment]
试过了，修好了
