### ISSUE TITLE
s xx --help提供的文档网站域名已过期

### ISSUE THREAD

**Issue by jinyang-dev** [Serverless-Devs/Serverless-Devs#823]
**Describe the bug**
s xx --help提供的文档网站无法访问
比如，`s init --help` 命令执行后，命令行界面显示：
Document: https://serverless.help/t/s/init

但是，https://serverless.help/t/s/init 跳转网站域名已过期。

**Screenshots**
![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103874020/318ea446-d56a-4360-937e-5c6369ead71b)

![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/103874020/38eb6cab-4a84-4637-912d-e9fce149a04b)

**Desktop (please complete the following information):**
 - OS: 
 - Version @serverless-devs/s: 3.0.7

**Additional context**

**Comment by zxypro1** [comment]
是已知问题，会在下一个版本修复

**Comment by zxypro1** [comment]
已在最新beta版本修复
