### ISSUE TITLE
什么时候能够支持火山 vefaas 的 node 的更高版本？

### ISSUE THREAD

**Issue by dragonforce2010** [Serverless-Devs/Serverless-Devs#879]
目前仅支持 node14 版本，啥时候可以支持 node20？
![image](https://github.com/user-attachments/assets/62b3d3f6-1a16-437e-a757-f8d1c3ccfa96)

**Comment by lowkeyrd** [comment]
这个是应用模板只透出了nodejs14，可以初始化后手动修改s.yaml的runtime。
该应用模板以及volcano-vefaas 组件 均由火山VeFaaS产品线维护，如果需要支持更多特性，可以给火山VeFaaS提交工单

**Comment by zxypro1** [comment]
确定将在下个正式版更新

**Comment by zxypro1** [comment]
已于3.1.2更新
