### ISSUE TITLE
Serverless Devs主仓库的测试用例完善

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/Serverless-Devs#91]
Serverless Devs主仓库的测试用例完善

需要针对该仓库，完善测试用例

_Originally posted by @anycodes in https://github.com/Serverless-Devs/Serverless-Devs/issues/90#issuecomment-844651066_

**Comment by hanxie-crypto** [comment]
补充一下需要添加单测的模块以及主要测试目标


### 模块名：
cli  【无配置指令执行】
### 模块使用说明 
通常的使用示例如下
s cli s-demo -h ；// 查看帮助
s cli s-demo test // 测试空
s cli s-demo testParams -p '{"serviceName": ""}' // 单纯入参
s cli s-demo testParams -p '{"serviceName": ""}' -a accessName // 入参+执行秘钥别名
指令执行的时候会把用户输入的  参数  '{"serviceName": ""}' 以及 本地的秘钥信息，项目信息统一封装起来 传递给 组件的方法 
最终的 数据格式应该符合 {props: {serviceName:'',credential:xxx,project:xxx,appName:xxx,command:xxx,args:xxx}}

### 测试目标
测试 cli-manager 类，通过 指定构造函数，并执行实例化的 cliManager 来判断结果是否符合预期
cliManager类构造参数 ,
interface CliParams {
    component: string; //组件名，可以直接使用s-demo
    command: string; // 测试的时候可传空，也可传 s-demo 的方法 如 test testParams
    aliasName: string; // 根据本地秘钥别名添加
    props: string //  如'{"serviceName": ""}' 
}

### 模块名
init  【初始化模板】
### 使用说明
s init
### 测试目标
测试  init-manager 的 init 方法是否可以返回正确的组件包

### 模块名
set 【设置源】
### 使用说明
s set registry

### 测试说明
测试 源的连通性，以及设置好之后的结果

### 模块名
uitl 【公共工具】

### 使用说明
公共工具

### 测试目标
测试  command-util,common,handler-set-config,logger,storage,url-parser  的方法



### 模块名
specification【规范解析】
