### ISSUE TITLE
s deploy 报错，默认发布到阿里云

### ISSUE THREAD

**Issue by zhangucan** [Serverless-Devs/Serverless-Devs#96]
s deploy 报错，默认发布到阿里云

![image](https://user-images.githubusercontent.com/26155364/119008264-976a8080-b9c4-11eb-93cf-6a3c3bc67ded.png)

**Comment by anycodes** [comment]
已经收到您的反馈。
@git-qfzhang @wss-git 两位大佬，这里支持看一下？

**Comment by git-qfzhang** [comment]
麻烦看一下报错信息哈

**Comment by anycodes** [comment]
> 麻烦看一下报错信息哈，@zhangucan

报错信息是`s deploy --debug`会更全一些吧？

**Comment by git-qfzhang** [comment]
> > 麻烦看一下报错信息哈，@zhangucan
> 
> 报错信息是`s deploy --debug`会更全一些吧？

不用，直接 retry 3 次后就会有报错信息了

**Comment by zhangucan** [comment]
看下了是AK权限问题
