### ISSUE TITLE
s 启动器参数识别问题

### ISSUE THREAD

**Issue by git-qfzhang** [Serverless-Devs/Serverless-Devs#97]
**Describe the bug**

```s [method] --option ${optionContent}``` 无法读取 optionContent，此时程序内读取的参数 ```option``` 的值为 ```true```，但是期望是 ```${optionContent}```，```s exec -- [method] --option ${optionContent}``` 则符合期望

**Screenshots**

![image](https://user-images.githubusercontent.com/52195264/119830818-39431d80-bf2f-11eb-9be6-889c932cf345.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version 10.15.7
 - s version: 2.0.35

**Comment by anycodes** [comment]
好的，这个问题，我这里先有先看一下，感谢反馈。

**Comment by anycodes** [comment]
出不来看是Core的问题可能，先关联到Core的部分。

**Comment by anycodes** [comment]
之前这个bug，已经修改过了，但是貌似有新合并代码的时候覆盖了之前的内容，导致这个bug的出现。我现在来支持一下，撤回关联Core的Issue

**Comment by anycodes** [comment]
Release 2.0.36
